In [2]:
from pprint import pprint
import json
from tqdm import tqdm

In [ ]:
# from datasets import load_dataset

# # Metadata for 171k documents
# meta = load_dataset("th1nhng0/vietnamese-legal-documents", "metadata", split="data")
# print(meta.to_pandas().head())

# # Cross-document relationships (amendments, citations, repeals, …)
# rels = load_dataset("th1nhng0/vietnamese-legal-documents", "relationships", split="data")
# print(rels.to_pandas().head())

# # Full-text HTML content for 170k documents
# content = load_dataset("th1nhng0/vietnamese-legal-documents", "content", split="data")
# print(content.to_pandas().head())

/home/minora/miniconda3/envs/python3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Generating data split: 100%|██████████| 171556/171556 [00:00<00:00, 1812187.44 examples/s]

       id                                              title  \
0    8733  Thông tư số 01/GD-ĐT Hướng dẫn việc dạy học ti...
1  105241  Nghị quyết số 13/2014/NQ-HĐND Quy định mức thu...
2  172978  Nghị quyết số 111/2024/NQ-HĐND Bãi bỏ Nghị quy...
3  171699  Quyết định số 25/2024/QĐ-UBND Quy định một số ...
4   80013  Quyết định số 616/2014/QĐ-UBND Về việc sửa đổi...

         so_ky_hieu ngay_ban_hanh loai_van_ban ngay_co_hieu_luc  \
0          01/GD-ĐT    03/02/1997     Thông tư       03/02/1997
1   13/2014/NQ-HĐND    05/12/2014   Nghị quyết       15/12/2014
2  111/2024/NQ-HĐND    11/12/2024   Nghị quyết       21/12/2024
3   25/2024/QĐ-UBND    30/10/2024   Quyết định       15/11/2024
4  616/2014/QĐ-UBND    28/03/2014   Quyết định       07/04/2014

  ngay_het_hieu_luc                                     nguon_thu_thap  \
0              None                                  Công báo điện tử;
1        01/01/2017                                               None
2              None  Văn phòng Đoàn đại biểu Quốc hội và Hội đồng n...
3              None                                               None
4              None                           Công báo số 06, năm 2014

  ngay_dang_cong_bao      nganh        linh_vuc        co_quan_ban_hanh  \
0               None       None  Chưa phân loại  Bộ Giáo dục và Đào tạo
1               None  Tài chính  Chưa phân loại      HĐND Tỉnh An Giang
2               None       None  Chưa phân loại       HĐND Tỉnh Gia Lai
3               None    Đất đai         Đất đai       UBND tỉnh Bắc Kạn
4               None     Nội vụ  Chưa phân loại    UBND Tỉnh Quảng Ninh

    chuc_danh          nguoi_ky     pham_vi thong_tin_ap_dung  \
0  Thứ trưởng     Trần Xuân Nhĩ  Trung ương              None
1    Chủ tịch      Phan Văn Sáu  Địa phương              None
2    Chủ tịch       Hồ Văn Niên  Địa phương              None
3    Chủ tịch  Nguyễn Đăng Bình  Địa phương              None
4    Chủ tịch    Nguyễn Văn Đọc  Địa phương              None

    tinh_trang_hieu_luc
0         Chưa xác định
1  Hết hiệu lực toàn bộ
2          Còn hiệu lực
3          Còn hiệu lực
4  Hết hiệu lực toàn bộ

Generating data split: 100%|██████████| 1033255/1033255 [00:00<00:00, 11781233.31 examples/s]

   doc_id other_doc_id relationship
0  106046        36867       Căn cứ
1   84010        20068       Căn cứ
2   92312        22281       Căn cứ
3  129653        70800       Căn cứ
4  172915        70803       Căn cứ

Generating data split: 100%|██████████| 170824/170824 [00:05<00:00, 32123.70 examples/s]

       id                                       content_html
0  132934  <!DOCTYPE html>\n<html>\n<head>\n    <meta cha...
1  131249  <html>\n <head></head>\n <body>\n  <div>\n   <...
2  130974  <html>\n <head></head>\n <body>\n  <table bord...
3  134516  <html>\n <head></head>\n <body>\n  <div>\n   <...
4  129591  <!DOCTYPE html>\n<html>\n<head>\n    <meta cha...

In [4]:
from datasets import Dataset, concatenate_datasets
from pathlib import Path

data_dir = Path("data")

datasets = {}

for name in ["metadata", "relationships", "content"]:
    folder = data_dir / name
    files = sorted(folder.rglob("*.arrow"))

    parts = []

    for file in files:
        print(f"Loading {name}: {file.name}")
        parts.append(Dataset.from_file(str(file)))

    datasets[name] = concatenate_datasets(parts)

meta_data = datasets["metadata"]
relationship = datasets["relationships"]
content = datasets["content"]

print(meta_data)
print(relationship)
print(content)

/home/minora/miniconda3/envs/python3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading metadata: vietnamese-legal-documents-data.arrow
Loading relationships: vietnamese-legal-documents-data.arrow
Loading content: vietnamese-legal-documents-data-00000-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00001-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00002-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00003-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00004-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00005-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00006-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00007-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00008-of-00010.arrow
Loading content: vietnamese-legal-documents-data-00009-of-00010.arrow
Dataset({
    features: ['id', 'title', 'so_ky_hieu', 'ngay_ban_hanh', 'loai_van_ban', 'ngay_co_hieu_luc', 'ngay_het_hieu_luc', 'nguon_thu_thap', 'ngay_dang_cong_bao', 'nganh', 'linh_vuc', 'co_quan_ban_hanh', 'chuc_danh', 'nguoi_ky', 'pham_vi', 'thong_tin_ap_dung', 'tinh_trang_hieu_luc'],
    num_rows: 171556
})
Dataset({
    features: ['doc_id', 'other_doc_id', 'relationship'],
    num_rows: 1033255
})
Dataset({
    features: ['id', 'content_html'],
    num_rows: 170824
})

In [3]:
pprint(content[0])

{'content_html': '<!DOCTYPE html>\n'
                 '<html>\n'
                 '<head>\n'
                 '    <meta charset="UTF-8">\n'
                 '    <meta name="viewport" content="width=device-width, '
                 'initial-scale=1.0">\n'
                 '    <title>Document Content</title>\n'
                 '    <style>\n'
                 '        body { font-family: Arial, sans-serif; margin: 20px; '
                 'line-height: 1.6; }\n'
                 '        p { margin: 10px 0; }\n'
                 '    </style>\n'
                 '</head>\n'
                 '<body>\n'
                 '<p>&nbsp;</p>\n'
                 '<p align="center"><strong>QUYẾT ĐỊNH</strong></p>\n'
                 '<p align="center">SỬA ĐỔI, BỔ SUNG MỘT SỐ ĐIỀU CỦA QUY ĐỊNH '
                 'ĐIỀU KIỆN, TIÊU CHUẨN, CHỨC DANH TRƯỞNG, PHÓ CÁC PHÒNG '
                 'CHUYÊN MÔN, ĐƠN VỊ THUỘC SỞ TÀI NGUYÊN VÀ MÔI TRƯỜNG; '
                 'TRƯỞNG, PHÓ PHÒNG TÀI NGUYÊN VÀ MÔI TRƯỜNG THUỘC ỦY BAN NHÂN '
                 'DÂN HUYỆN, THÀNH PHỐ BAN HÀNH KÈM THEO QUYẾT ĐỊNH SỐ '
                 '27/2016/QĐ-UBND NGÀY 07 THÁNG 9 NĂM 2016 CỦA ỦY BAN NHÂN DÂN '
                 'TỈNH BẮC KẠN</p>\n'
                 '<p align="center"><strong>ỦY BAN NHÂN DÂN TỈNH BẮC '
                 'KẠN</strong></p>\n'
                 '<p><em>Căn cứ Luật Tổ chức chính quyền địa phương ngày 19 '
                 'tháng 6 năm 2015;</em></p>\n'
                 '<p><em>Căn cứ Nghị định số 24/2010/NĐ-CP ngày 15 tháng 3 năm '
                 '2010 của Chính phủ quy định về tuyển dụng, sử dụng và quản '
                 'lý công chức;</em></p>\n'
                 '<p><em>Căn cứ Nghị định số 29/2012/NĐ-CP ngày 12 tháng 4 năm '
                 '2012 của Chính phủ về tuyển dụng, sử dụng và quản lý viên '
                 'chức;</em></p>\n'
                 '<p><em>Căn cứ Quyết định số 27/2003/QĐ-TTg ngày 19 tháng 02 '
                 'năm 2003 của Thủ tướng Chính phủ về việc ban hành Quy chế bổ '
                 'nhiệm, bổ nhiệm lại, luân chuyển, từ chức, miễn nhiệm cán '
                 'bộ, công chức lãnh đạo;</em></p>\n'
                 '<p><em>Căn cứ Thông tư liên tịch số 50/2014/TTLT-BTNMT-BNV '
                 'ngày 28 tháng 8 năm 2014 của Bộ Tài nguyên và Môi trường và '
                 'Bộ Nội vụ hướng dẫn chức năng, nhiệm vụ, quyền hạn và cơ cấu '
                 'tổ chức của Sở Tài nguyên và Môi trường thuộc Ủy ban nhân '
                 'dân tỉnh, thành phố trực thuộc Trung ương, Phòng Tài nguyên '
                 'và Môi trường thuộc Ủy ban nhân dân huyện, quận, thị xã, '
                 'thành phố thuộc tỉnh;</em></p>\n'
                 '<p><em>Theo đề nghị của Giám đốc Sở Tài nguyên và Môi trường '
                 'tại Tờ trình số 321/TTr-STNMT ngày 02 tháng 11 năm '
                 '2018.</em></p>\n'
                 '<p align="center"><strong>QUYẾT ĐỊNH:</strong></p>\n'
                 '<p><strong>Điều 1. Sửa đổi, bổ sung một số điều của Quy định '
                 'điều kiện, tiêu chuẩn chức danh Trưởng, Phó các phòng chuyên '
                 'môn, đơn vị thuộc Sở Tài nguyên và Môi trường; Trưởng, Phó '
                 'phòng Tài nguyên và Môi trường thuộc Ủy ban nhân dân huyện, '
                 'thành phố ban hành kèm theo Quyết định số 27/2016/QĐ-UBND '
                 'ngày 07/9/2016 của Ủy ban nhân dân tỉnh Bắc '
                 'Kạn:</strong></p>\n'
                 '<p>1. Khoản 6 Điều 4 được sửa đổi, bổ sung như sau:</p>\n'
                 '<p>“6. Tuổi bổ nhiệm:</p>\n'
                 '<p>a) Các chức vụ Trưởng phòng, Phó trưởng phòng chuyên môn, '
                 'đơn vị thuộc Sở Tài nguyên và Môi trường, tuổi bổ nhiệm lần '
                 'đầu không quá 55 tuổi đối với nam và không quá 50 tuổi đối '
                 'với nữ;</p>\n'
                 '<p>b) Các chức vụ Trưởng phòng, Phó trưởng phòng Tài nguyên '
                 'và Môi trường các huyện, thành phố, tuổi bổ nhiệm lần đầu '
                 'không quá 45 tuổi (đối với cả nam và nữ);</p>\n'
                 '<p>c) Trường hợp công chức, viên chức đã thôi giữ chức vụ '
                 'lãnh đạo, sau một thời gian công tác nếu được xem xét để bổ '
                 'nhiệm giữ chức vụ lãnh đạo, thì điều kiện về tuổi thực hiện '
                 'như quy định khi bổ nhiệm lần đầu.”</p>\n'
                 '<p>2. Sửa đổi, bổ sung điểm e Điều 5 như sau:</p>\n'
                 '<p>“e) Có trình độ lý luận chính trị cao cấp hoặc cử '
                 'nhân.”</p>\n'
                 '<p><strong>Điều 2.</strong> Chánh Văn phòng Ủy ban nhân dân '
                 'tỉnh, Giám đốc Sở Nội vụ, Giám đốc Sở Tài nguyên và Môi '
                 'trường, Chủ tịch Ủy ban nhân dân các huyện, thành phố, thủ '
                 'trưởng các cơ quan, đơn vị có liên quan chịu trách nhiệm thi '
                 'hành Quyết định này.</p>\n'
                 '<p><strong>Điều 3.</strong> Quyết định này có hiệu lực từ '
                 'ngày 10 tháng 12 năm 2018./.</p>\n'
                 '<p>&nbsp;</p>\n'
                 '<p>&nbsp;</p>\n'
                 '</body>\n'
                 '</html>',
 'id': '132934'}

In [51]:
pprint(meta_data[0])

{'chuc_danh': 'Thứ trưởng',
 'co_quan_ban_hanh': 'Bộ Giáo dục và Đào tạo',
 'id': '8733',
 'linh_vuc': 'Chưa phân loại',
 'loai_van_ban': 'Thông tư',
 'nganh': None,
 'ngay_ban_hanh': '03/02/1997',
 'ngay_co_hieu_luc': '03/02/1997',
 'ngay_dang_cong_bao': None,
 'ngay_het_hieu_luc': None,
 'nguoi_ky': 'Trần Xuân Nhĩ',
 'nguon_thu_thap': 'Công báo điện tử;',
 'pham_vi': 'Trung ương',
 'so_ky_hieu': '01/GD-ĐT',
 'thong_tin_ap_dung': None,
 'tinh_trang_hieu_luc': 'Chưa xác định',
 'title': 'Thông tư số 01/GD-ĐT Hướng dẫn việc dạy học tiếng nói và chữ viết '
          'dân tộc thiểu số'}

In [53]:
for doc in meta_data:
    if doc["id"] == "132934":
        pprint(doc)
        break

{'chuc_danh': 'Chủ tịch',
 'co_quan_ban_hanh': 'UBND tỉnh Bắc Kạn',
 'id': '132934',
 'linh_vuc': 'Chưa phân loại',
 'loai_van_ban': 'Quyết định',
 'nganh': None,
 'ngay_ban_hanh': '29/11/2018',
 'ngay_co_hieu_luc': '10/12/2018',
 'ngay_dang_cong_bao': None,
 'ngay_het_hieu_luc': '27/06/2025',
 'nguoi_ky': 'Lý Thái Hải',
 'nguon_thu_thap': None,
 'pham_vi': 'Địa phương',
 'so_ky_hieu': '37/2018/QĐ-UBND',
 'thong_tin_ap_dung': None,
 'tinh_trang_hieu_luc': 'Hết hiệu lực toàn bộ',
 'title': 'Quyết định số 37/2018/QĐ-UBND Sửa đổi, bổ sung một số điều của Quy '
          'định điều kiện, tiêu chuẩn, chức danh Trưởng, Phó các phòng chuyên '
          'môn, đơn vị thuộc Sở Tài nguyên và Môi trường; Trưởng, Phó phòng '
          'Tài nguyên và Môi trường thuộc Ủy ban nhân dân huyện, thành phố ban '
          'hành kèm theo Quyết định số 27/2016/QĐ-UBND ngày 07/9/2016 của Ủy '
          'ban nhân dân tỉnh Bắc Kạn'}

In [20]:
type_relationship = set()
for sample in tqdm(relationship):
    type_relationship.add(sample["relationship"])
pprint(type_relationship)

100%|██████████| 1033255/1033255 [00:15<00:00, 67932.08it/s]

{'Bãi bỏ',
 'Bản dịch',
 'Công bố',
 'Căn cứ',
 'Dẫn chiếu',
 'Giải thích',
 'Hướng dẫn áp dụng',
 'Hợp nhất',
 'Quy định chi tiết, hướng dẫn thi hành',
 'Sửa đổi, bổ sung',
 'Thay thế',
 'Tạm ngưng hiệu lực',
 'Văn bản HD, QĐ chi tiết',
 'Văn bản bị hết hiệu lực 1 phần',
 'Văn bản bị đình chỉ',
 'Văn bản bị đình chỉ 1 phần',
 'Văn bản bổ sung',
 'Văn bản căn cứ',
 'Văn bản dẫn chiếu',
 'Văn bản hết hiệu lực',
 'Văn bản liên quan khác',
 'Văn bản quy định hết hiệu lực',
 'Văn bản quy định hết hiệu lực 1 phần',
 'Văn bản sửa đổi',
 'Văn bản đình chỉ',
 'Văn bản đình chỉ 1 phần',
 'Văn bản được HD, QĐ chi tiết',
 'Văn bản được bổ sung',
 'Văn bản được sửa đổi',
 'Đình chỉ thi hành',
 'Đính chính'}

# Parser

In [5]:
import os
import json
from parser.parser import *
from parser.utils import clean_newlines
from parser.scaffolder import *

def preprocess_markdown(markdown):
    markdown = markdown.replace("*", "").replace("## ", "").replace("“", "\"").replace("”", "\"").strip()
    markdown = clean_newlines(markdown)
    return markdown

def parsing_pipeline(markdown):
    markdown = preprocess_markdown(markdown)
    # pprint(markdown) #DEBUG
    legal_tree = parser(markdown)
    return legal_tree

In [6]:
from markitdown import MarkItDown
import io

md = MarkItDown()
def convert2markdown(html_content):
    file_stream = io.BytesIO(html_content.encode("utf-8"))
    markdown = md.convert(file_stream, file_extension=".html")
    return markdown.text_content

In [9]:
import json
from tqdm.auto import tqdm

output_path = "data/documents.jsonl"

with open(output_path, "w", encoding="utf-8") as f:
    for content_sample in tqdm(content):
        new_content = content_sample.copy()
        new_content["content_markdown"] = convert2markdown(new_content["content_html"])
        new_content["legal_tree"] = parsing_pipeline(new_content["content_markdown"])
        # Ghi ngay document này xuống disk
        f.write(json.dumps(new_content,ensure_ascii=False,default=lambda obj: obj.__dict__) + "\n")

100%|██████████| 170824/170824 [1:25:42<00:00, 33.22it/s]

In [ ]:
meta_dict = {meta["id"]: meta for meta in meta_data}

documents1 = []
documents2 = []
documents3 = []

total = 170000
chunk_size = total // 3

with open("data/documents.jsonl", "r", encoding="utf-8") as f:
    for count, line in enumerate(tqdm(f, total=total), start=0):

        sample = json.loads(line)

        meta = meta_dict.get(sample["id"])
        if meta is None:
            continue

        document = {
            "id": meta["id"],
            "title": meta["title"],
            "content": sample["content_markdown"],
            "legal_tree": sample["legal_tree"],
            "ngay_ban_hanh": meta["ngay_ban_hanh"],
            "ngay_co_hieu_luc": meta["ngay_co_hieu_luc"],
            "ngay_dang_cong_bao": meta["ngay_dang_cong_bao"],
            "ngay_het_hieu_luc": meta["ngay_het_hieu_luc"],
            "so_ky_hieu": meta["so_ky_hieu"],
            "tinh_trang_hieu_luc": meta["tinh_trang_hieu_luc"],
            "pham_vi": meta["pham_vi"]
        }

        if count < chunk_size:
            documents1.append(document)

        elif count < chunk_size * 2:
            documents2.append(document)

        else:
            documents3.append(document)

170824it [00:51, 3303.66it/s]

In [11]:
output_path = "data/documents_merged.jsonl"

with open(output_path, "w", encoding="utf-8") as f:
    for documents in [documents1, documents2, documents3]:
        for document in tqdm(documents):
            f.write(json.dumps(document, ensure_ascii=False) + "\n")

100%|██████████| 56666/56666 [00:10<00:00, 5332.58it/s]
100%|██████████| 56666/56666 [00:10<00:00, 5284.26it/s]
100%|██████████| 57492/57492 [00:11<00:00, 5205.07it/s]

Load data

In [3]:
documents = []
with open("data/documents_merged_v4.jsonl", "r", encoding="utf-8") as f:
    for line in tqdm(f):
        sample = json.loads(line)
        documents.append(sample)

169906it [00:18, 9216.56it/s]

In [3]:
pprint(documents[0])

{'content': '**QUYẾT ĐỊNH**\n'
            '\n'
            'SỬA ĐỔI, BỔ SUNG MỘT SỐ ĐIỀU CỦA QUY ĐỊNH ĐIỀU KIỆN, TIÊU CHUẨN, '
            'CHỨC DANH TRƯỞNG, PHÓ CÁC PHÒNG CHUYÊN MÔN, ĐƠN VỊ THUỘC SỞ TÀI '
            'NGUYÊN VÀ MÔI TRƯỜNG; TRƯỞNG, PHÓ PHÒNG TÀI NGUYÊN VÀ MÔI TRƯỜNG '
            'THUỘC ỦY BAN NHÂN DÂN HUYỆN, THÀNH PHỐ BAN HÀNH KÈM THEO QUYẾT '
            'ĐỊNH SỐ 27/2016/QĐ-UBND NGÀY 07 THÁNG 9 NĂM 2016 CỦA ỦY BAN NHÂN '
            'DÂN TỈNH BẮC KẠN\n'
            '\n'
            '**ỦY BAN NHÂN DÂN TỈNH BẮC KẠN**\n'
            '\n'
            '*Căn cứ Luật Tổ chức chính quyền địa phương ngày 19 tháng 6 năm '
            '2015;*\n'
            '\n'
            '*Căn cứ Nghị định số 24/2010/NĐ-CP ngày 15 tháng 3 năm 2010 của '
            'Chính phủ quy định về tuyển dụng, sử dụng và quản lý công chức;*\n'
            '\n'
            '*Căn cứ Nghị định số 29/2012/NĐ-CP ngày 12 tháng 4 năm 2012 của '
            'Chính phủ về tuyển dụng, sử dụng và quản lý viên chức;*\n'
            '\n'
            '*Căn cứ Quyết định số 27/2003/QĐ-TTg ngày 19 tháng 02 năm 2003 '
            'của Thủ tướng Chính phủ về việc ban hành Quy chế bổ nhiệm, bổ '
            'nhiệm lại, luân chuyển, từ chức, miễn nhiệm cán bộ, công chức '
            'lãnh đạo;*\n'
            '\n'
            '*Căn cứ Thông tư liên tịch số 50/2014/TTLT-BTNMT-BNV ngày 28 '
            'tháng 8 năm 2014 của Bộ Tài nguyên và Môi trường và Bộ Nội vụ '
            'hướng dẫn chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Sở '
            'Tài nguyên và Môi trường thuộc Ủy ban nhân dân tỉnh, thành phố '
            'trực thuộc Trung ương, Phòng Tài nguyên và Môi trường thuộc Ủy '
            'ban nhân dân huyện, quận, thị xã, thành phố thuộc tỉnh;*\n'
            '\n'
            '*Theo đề nghị của Giám đốc Sở Tài nguyên và Môi trường tại Tờ '
            'trình số 321/TTr-STNMT ngày 02 tháng 11 năm 2018.*\n'
            '\n'
            '**QUYẾT ĐỊNH:**\n'
            '\n'
            '**Điều 1. Sửa đổi, bổ sung một số điều của Quy định điều kiện, '
            'tiêu chuẩn chức danh Trưởng, Phó các phòng chuyên môn, đơn vị '
            'thuộc Sở Tài nguyên và Môi trường; Trưởng, Phó phòng Tài nguyên '
            'và Môi trường thuộc Ủy ban nhân dân huyện, thành phố ban hành kèm '
            'theo Quyết định số 27/2016/QĐ-UBND ngày 07/9/2016 của Ủy ban nhân '
            'dân tỉnh Bắc Kạn:**\n'
            '\n'
            '1. Khoản 6 Điều 4 được sửa đổi, bổ sung như sau:\n'
            '\n'
            '“6. Tuổi bổ nhiệm:\n'
            '\n'
            'a) Các chức vụ Trưởng phòng, Phó trưởng phòng chuyên môn, đơn vị '
            'thuộc Sở Tài nguyên và Môi trường, tuổi bổ nhiệm lần đầu không '
            'quá 55 tuổi đối với nam và không quá 50 tuổi đối với nữ;\n'
            '\n'
            'b) Các chức vụ Trưởng phòng, Phó trưởng phòng Tài nguyên và Môi '
            'trường các huyện, thành phố, tuổi bổ nhiệm lần đầu không quá 45 '
            'tuổi (đối với cả nam và nữ);\n'
            '\n'
            'c) Trường hợp công chức, viên chức đã thôi giữ chức vụ lãnh đạo, '
            'sau một thời gian công tác nếu được xem xét để bổ nhiệm giữ chức '
            'vụ lãnh đạo, thì điều kiện về tuổi thực hiện như quy định khi bổ '
            'nhiệm lần đầu.”\n'
            '\n'
            '2. Sửa đổi, bổ sung điểm e Điều 5 như sau:\n'
            '\n'
            '“e) Có trình độ lý luận chính trị cao cấp hoặc cử nhân.”\n'
            '\n'
            '**Điều 2.** Chánh Văn phòng Ủy ban nhân dân tỉnh, Giám đốc Sở Nội '
            'vụ, Giám đốc Sở Tài nguyên và Môi trường, Chủ tịch Ủy ban nhân '
            'dân các huyện, thành phố, thủ trưởng các cơ quan, đơn vị có liên '
            'quan chịu trách nhiệm thi hành Quyết định này.\n'
            '\n'
            '**Điều 3.** Quyết định này có hiệu lực từ ngày 10 tháng 12 năm '
            '2018./.',
 'id': '132934',
 'list_dieu': [{'partId': '1',
                'partType': 'điều',
                'text': 'Điều 1. Sửa đổi, bổ sung một số điều của Quy định '
                        'điều kiện, tiêu chuẩn chức danh Trưởng, Phó các phòng '
                        'chuyên môn, đơn vị thuộc Sở Tài nguyên và Môi trường; '
                        'Trưởng, Phó phòng Tài nguyên và Môi trường thuộc Ủy '
                        'ban nhân dân huyện, thành phố ban hành kèm theo Quyết '
                        'định số 27/2016/QĐ-UBND ngày 07/9/2016 của Ủy ban '
                        'nhân dân tỉnh Bắc Kạn:\n'
                        '1. Khoản 6 Điều 4 được sửa đổi, bổ sung như sau:\n'
                        '"6. Tuổi bổ nhiệm:\n'
                        'a) Các chức vụ Trưởng phòng, Phó trưởng phòng chuyên '
                        'môn, đơn vị thuộc Sở Tài nguyên và Môi trường, tuổi '
                        'bổ nhiệm lần đầu không quá 55 tuổi đối với nam và '
                        'không quá 50 tuổi đối với nữ;\n'
                        'b) Các chức vụ Trưởng phòng, Phó trưởng phòng Tài '
                        'nguyên và Môi trường các huyện, thành phố, tuổi bổ '
                        'nhiệm lần đầu không quá 45 tuổi (đối với cả nam và '
                        'nữ);\n'
                        'c) Trường hợp công chức, viên chức đã thôi giữ chức '
                        'vụ lãnh đạo, sau một thời gian công tác nếu được xem '
                        'xét để bổ nhiệm giữ chức vụ lãnh đạo, thì điều kiện '
                        'về tuổi thực hiện như quy định khi bổ nhiệm lần '
                        'đầu."\n'
                        '2. Sửa đổi, bổ sung điểm e Điều 5 như sau:\n'
                        '"e) Có trình độ lý luận chính trị cao cấp hoặc cử '
                        'nhân."',
                'treeId': 'điều1'},
               {'partId': '2',
                'partType': 'điều',
                'text': 'Điều 2. Chánh Văn phòng Ủy ban nhân dân tỉnh, Giám '
                        'đốc Sở Nội vụ, Giám đốc Sở Tài nguyên và Môi trường, '
                        'Chủ tịch Ủy ban nhân dân các huyện, thành phố, thủ '
                        'trưởng các cơ quan, đơn vị có liên quan chịu trách '
                        'nhiệm thi hành Quyết định này.',
                'treeId': 'điều2'},
               {'partId': '3',
                'partType': 'điều',
                'text': 'Điều 3. Quyết định này có hiệu lực từ ngày 10 tháng '
                        '12 năm 2018./.',
                'treeId': 'điều3'}],
 'ngay_ban_hanh': '29/11/2018',
 'ngay_co_hieu_luc': '10/12/2018',
 'ngay_dang_cong_bao': None,
 'ngay_het_hieu_luc': '27/06/2025',
 'pham_vi': 'Địa phương',
 'so_ky_hieu': '37/2018/QĐ-UBND',
 'tinh_trang_hieu_luc': 'Hết hiệu lực toàn bộ',
 'title': 'Quyết định số 37/2018/QĐ-UBND Sửa đổi, bổ sung một số điều của Quy '
          'định điều kiện, tiêu chuẩn, chức danh Trưởng, Phó các phòng chuyên '
          'môn, đơn vị thuộc Sở Tài nguyên và Môi trường; Trưởng, Phó phòng '
          'Tài nguyên và Môi trường thuộc Ủy ban nhân dân huyện, thành phố ban '
          'hành kèm theo Quyết định số 27/2016/QĐ-UBND ngày 07/9/2016 của Ủy '
          'ban nhân dân tỉnh Bắc Kạn'}

In [9]:
for doc in documents:
    if doc["id"] == "14290":
        pprint(doc["list_dieu"])
        break

[{'partId': '1',
  'partType': 'điều',
  'text': 'Điều 1. Phạm vi điều chỉnh và đối tượng áp dụng\n'
          '1. Nghị định này quy định cụ thể điều kiện, trình tự, thủ tục, cơ '
          'quan thẩm định, cơ quan cấp Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung, Giấy chứng nhận đăng '
          'ký hoạt động hàng không chung.\n'
          '2. Nghị định này áp dụng đối với mọi tổ chức, cá nhân liên quan đến '
          'việc cấp Giấy phép kinh doanh vận chuyển hàng không, Giấy phép kinh '
          'doanh hàng không chung, Giấy chứng nhận đăng ký hoạt động hàng '
          'không chung.',
  'treeId': 'chươngI_điều1'},
 {'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Phạm vi hoạt động kinh doanh vận chuyển hàng không, hoạt '
          'động hàng không chung\n'
          '1. Hoạt động kinh doanh vận chuyển hàng không gồm vận chuyển hàng '
          'không, quảng cáo, tiếp thị, bán sản phẩm vận chuyển hàng không trên '
          'thị trường nhằm mục đích sinh lợi.\n'
          '2. Hoạt động hàng không chung bao gồm các loại hình sau đây:\n'
          'a) Hoạt động hàng không chung vì mục đích thương mại là hoạt động '
          'cung cấp dịch vụ hàng không chung, quảng cáo, tiếp thi hoặc bán '
          'dịch vụ hàng không chung trên thị trường nhằm mục đích sinh lợi;\n'
          'b) Hoạt động hàng không chung không vì mục đích thương mại là hoạt '
          'động hàng không chung phục vụ cho hoạt động của tổ chức, cá nhân '
          'không nhằm mục đích sinh lợi.',
  'treeId': 'chươngI_điều2'},
 {'partId': '3',
  'partType': 'điều',
  'text': 'Điều 3. Cơ quan thẩm định, cấp giấy phép, giấy chứng nhận\n'
          '1. Cục Hàng không Việt Nam là cơ quan thuộc Bộ Giao thông vận tải '
          'thực hiện việc thẩm định hồ sơ đề nghị cấp Giấy phép kinh doanh vận '
          'chuyển hàng không, Giấy phép kinh doanh hàng không chung, Giấy '
          'chứng nhận đăng ký hoạt động hàng không chung, Giấy chứng nhận đầu '
          'tư cho dự án đầu tư có vốn đầu tư nước ngoài trong lĩnh vực kinh '
          'doanh vận chuyển hàng không, Giấy chứng nhận đầu tư cho dự án đầu '
          'tư có vốn đầu tư nước ngoài trong lĩnh vực kinh doanh hàng không '
          'chung.\n'
          '2. Bộ trưởng Bộ Giao thông vận tải cấp Giấy phép kinh doanh vận '
          'chuyển hàng không, Giấy chứng nhận đầu tư cho dự án đầu tư có vốn '
          'đầu tư nước ngoài trong lĩnh vực kinh doanh vận chuyển hàng không '
          'sau khi được Thủ tướng Chỉnh phủ cho phép.\n'
          '3. Cục trưởng Cục Hàng không Việt Nam thực hiện việc cấp Giấy phép '
          'kinh doanh hàng không chung, Giấy chứng nhận đầu tư cho dự án đầu '
          'tư có vốn đầu tư nước ngoài trong lĩnh vực kinh doanh hàng không '
          'chung, Giấy chứng nhận đăng ký hoạt động hàng không chung.',
  'treeId': 'chươngI_điều3'},
 {'partId': '4',
  'partType': 'điều',
  'text': 'Điều 4. Giấy chứng nhận đầu tư cho dự án đầu tư có vốn đầu tư nước '
          'ngoài\n'
          '1. Giấy chứng nhận đầu tư cho dự án đầu tư có vốn đầu tư nước ngoài '
          'đồng thời là Giấy phép kinh doanh vận chuyển hàng không, Giấy phép '
          'kinh doanh hàng không chung tương ứng.\n'
          '2. Điều kiện, trình tự, thủ tục cấp Giấy chứng nhận đầu tư quy định '
          'tại khoản 1 Điều này được thực hiện như đối với việc cấp Giấy phép '
          'kinh doanh vận chuyển hàng không, Giấy phép kinh doanh hàng không '
          'chung quy định tại Nghị định này.',
  'treeId': 'chươngI_điều4'},
 {'partId': '5',
  'partType': 'điều',
  'text': 'Điều 5. Yêu cầu chung\n'
          '1. Doanh nghiệp đề nghị cấp Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung phải đáp ứng các điều '
          'kiện quy định tương ứng tại khoản 1 Điều 110, khoản 2 Điều 198 của '
          'Luật Hàng không dân dụng Việt Nam và các điều kiện cụ thể quy định '
          'tại Nghị định này.\n'
          '2. Hãng hàng không đã được cấp Giấy phép kinh doanh vận chuyển hàng '
          'không đề nghị cấp Giấy phép kinh doanh hàng không chung chỉ cần đáp '
          'ứng các điều kiện quy định tương ứng tại điểm a khoản 1 , khoản 2 '
          'Điều 6, Điều 9 của Nghị định này.',
  'treeId': 'chươngII_điều5'},
 {'partId': '6',
  'partType': 'điều',
  'text': 'Điều 6. Phương án bảo đảm có tàu bay khai thác\n'
          '1. Phương án bảo đảm có tàu bay khai thác trong 5 năm kể từ ngày dự '
          'kiến bắt đầu kinh doanh bao gồm các nội dung sau đây:\n'
          'a) Số lượng, chủng loại tàu bay;\n'
          'b) Hình thức chiếm hữu (mua, thuê mua hoặc thuê);\n'
          'c) Phương án khai thác, bảo dưỡng và nguồn nhân lực bảo đảm khai '
          'thác, bảo dưỡng tàu bay;\n'
          'd) Nguồn vốn bảo đảm chiếm hữu tàu bay;\n'
          'đ) Bảo đảm số lượng tàu bay thuê có tổ lái đến hết năm khai thác '
          'thứ ba không chiếm quá 30% đội tàu bay.\n'
          '2. Tuổi của tàu bay đã qua sử dụng nhập khẩu vào Việt Nam được quy '
          'định như sau:\n'
          'a) Đối với tàu bay thực hiện vận chuyển hành khách: không quá 10 '
          'năm tính từ ngày xuất xưởng đến thời điểm nhập khẩu vào Việt Nam '
          'theo hợp đồng mua, thuê mua; không quá 20 năm tính từ ngày xuất '
          'xưởng đến thời điểm kết thúc hợp đồng thuê theo hợp đồng thuê;\n'
          'b) Đối với tàu bay vận chuyển hàng hoá, bưu phẩm, bưu kiện, hoạt '
          'động hàng không chung vì mục đích thương mại: không quá 15 năm tính '
          'từ ngày xuất xưởng đến thời điểm nhập khẩu vào Việt Nam theo hợp '
          'đồng mua, thuê mua; không quá 25 năm tính từ ngày xuất xưởng đến '
          'thời điểm kết thúc hợp đồng thuê theo hợp đồng thuê;\n'
          'c) Đối với tàu bay ngoài quy định tại điểm a, b khoản 2 Điều này: '
          'không quá 20 năm tính từ ngày xuất xưởng đến thời điểm nhập khẩu '
          'vào Việt Nam theo hợp đồng mua, thuê mua; không quá 30 năm tính từ '
          'ngày xuất xưởng đến thời điểm kết thúc hợp đồng thuê theo hợp đồng '
          'thuê.',
  'treeId': 'chươngII_điều6'},
 {'partId': '7',
  'partType': 'điều',
  'text': 'Điều 7. Điều kiện về tổ chức bộ máy bảo đảm khai thác tàu bay, kinh '
          'doanh vận chuyển hàng không, kinh doanh hàng không chung\n'
          '1. Có tổ chức bộ máy quản lý đủ năng lực giám sát hoạt động khai '
          'thác tàu bay, bảo dưỡng tàu bay, huấn luyện bay, khai thác mặt đất; '
          'phát triển sản phẩm, tiếp thị và bán dịch vụ vận chuyển hàng không; '
          'hệ thống thanh toán tài chính.\n'
          '2. Người phụ trách các hoạt động quy định tại khoản 1 Điều này phải '
          'có chứng chỉ chuyên môn phù hợp được Bộ Giao thông vận tải cấp hoặc '
          'công nhận.',
  'treeId': 'chươngII_điều7'},
 {'partId': '8',
  'partType': 'điều',
  'text': 'Điều 8. Vốn pháp định\n'
          '1. Vốn pháp định đối với hãng hàng không kinh doanh vận chuyển hàng '
          'không được quy định như sau:\n'
          'a) Khai thác từ 1 đến 10 tàu bay:\n'
          '- 500 tỷ Đồng Việt Nam đối với doanh nghiệp có khai thác vận chuyển '
          'hàng không quốc tế;\n'
          '- 200 tỷ Đồng Việt Nam đối với doanh nghiệp chỉ khai thác vận '
          'chuyển hàng không nội địa.\n'
          'b) Khai thác từ 11 đến 30 tàu bay:\n'
          '- 800 tỷ Đồng Việt Nam đối với doanh nghiệp có khai thác vận chuyển '
          'hàng không quốc tế;\n'
          '- 400 tỷ Đồng Việt Nam đối với doanh nghiệp chỉ khai thác vận '
          'chuyển hàng không nội địa.\n'
          'c) Khai thác trên 30 tàu bay:\n'
          '- 1.000 tỷ Đồng Việt Nam đối với doanh nghiệp có khai thác vận '
          'chuyển hàng không quốc tế;\n'
          '- 500 tỷ Đồng Việt Nam đối với doanh nghiệp chỉ khai thác vận '
          'chuyển hàng không nội địa.\n'
          '2. Vốn pháp định đối với doanh nghiệp kinh doanh hàng không chung: '
          '50 tỷ Đồng Việt Nam.',
  'treeId': 'chươngII_điều8'},
 {'partId': '9',
  'partType': 'điều',
  'text': 'Điều 9. Nội dung của phương án kinh doanh và chiến lược phát triển '
          'sản phẩm\n'
          '1. Nhu cầu và xu hướng phát triển của thị trường.\n'
          '2. Đánh giá thực tiễn và mức độ cạnh tranh dịch vụ được cung cấp '
          'trên thị trường.\n'
          '3. Chiến lược phát triển sản phẩm vận chuyển hàng không và kế hoạch '
          'phát triển kinh doanh của 5 năm đầu.',
  'treeId': 'chươngII_điều9'},
 {'partId': '10',
  'partType': 'điều',
  'text': 'Điều 10. Doanh nghiệp có vốn đầu tư nước ngoài\n'
          '1. Hãng hàng không kinh doanh vận chuyển hàng không, doanh nghiệp '
          'kinh doanh hàng không chung có vốn đầu tư nước ngoài phải đáp ứng '
          'các điều kiện quy định tại khoản 2 Điều 110 của Luật Hàng không dân '
          'dụng Việt Nam và các điều kiện cụ thể sau đây:\n'
          'a) Điều lệ hoạt động của doanh nghiệp phải quy định rõ thành viên '
          'của bộ máy điều hành của doanh nghiệp, trong đó số thành viên là '
          'người nước ngoài không được vượt quá một phần ba tổng số thành '
          'viên;\n'
          'b) Bên nước ngoài không chiếm quá 49% vốn điều lệ đối với hãng hàng '
          'không, hoặc 49% vốn điều lệ đối với doanh nghiệp kinh doanh hàng '
          'không chung; một cá nhân hoặc pháp nhân nước ngoài không chiếm quá '
          '30% vốn điều lệ.\n'
          '2. Bộ máy điều hành nêu tại điểm a khoản 1 của Điều này bao gồm:\n'
          'a) Giám đốc, Phó giám đốc;\n'
          'b) Kế toán trưởng;\n'
          'c) Người phụ trách giám sát hoạt động khai thác, bảo dưỡng, huấn '
          'luyện tổ bay, khai thác mặt đất; phát triển sản phẩm, tiếp thị và '
          'bán dịch vụ vận chuyển hàng không;\n'
          'd) Các thành viên khác thuộc Ban giám đốc điều hành theo quy định '
          'của Điều lệ hoạt động của doanh nghiệp.',
  'treeId': 'chươngII_điều10'},
 {'partId': '11',
  'partType': 'điều',
  'text': 'Điều 11. Hồ sơ đề nghị cấp Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung\n'
          '1. Người nộp hồ sơ đề nghị cấp Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung phải gửi hồ sơ đến Cục '
          'Hàng không Việt Nam.\n'
          '2. Hồ sơ bao gồm:\n'
          'a) Đơn đề nghị cấp giấy phép, bao gồm các thông tin: tên doanh '
          'nghiệp, tên giao dịch, địa điểm trụ sở chính; người đại diện theo '
          'pháp luật; loại hình doanh nghiệp; chi nhánh, văn phòng đại diện '
          '(nếu có);\n'
          'b) Bản sao Giấy chứng nhận đăng ký hoạt động hàng không chung trong '
          'trường hợp đề nghị cấp giấy phép kinh doanh hoạt động hàng không '
          'chung;\n'
          'c) Danh sách thành viên, cổ đông; quốc tịch và phần vốn góp của mỗi '
          'thành viên, cổ đông đối với công ty hợp danh, công ty trách nhiệm '
          'hữu hạn, công ty cổ phần;\n'
          'd) Bản sao Giấy chứng nhận đăng ký kinh doanh;\n'
          'đ) Tài liệu chứng minh về việc đáp ứng các điều kiện cấp phép quy '
          'định tại Chương II của Nghị định này;\n'
          'e) Bản sao Điều lệ hoạt động của doanh nghiệp;\n'
          'g) Dự thảo Điều lệ vận chuyển hàng không;\n'
          'h) Văn bản xác nhận tư cách pháp lý của chủ sở hữu, cổ đông, các '
          'nhà đầu tư;\n'
          'i) Báo cáo năng lực tài chính của chủ sở hữu, thành viên Hội đồng '
          'thành viên, cổ đông, các nhà đầu tư;\n'
          'k) Xác nhận của cơ quan, tổ chức có thẩm quyền hoặc văn bản hợp '
          'pháp chứng minh về số vốn của doanh nghiệp;\n'
          'l) Bản sao văn bằng, chứng chỉ chuyên môn của những người phụ trách '
          'quy định tại Điều 7 của Nghị định này;\n'
          'm) Biên lai hoặc giấy tờ xác nhận về việc nộp lệ phí.',
  'treeId': 'chươngIII_điều11'},
 {'partId': '12',
  'partType': 'điều',
  'text': 'Điều 12. Thẩm định hồ sơ đăng ký cấp Giấy phép kinh doanh vận '
          'chuyển hàng không\n'
          '1. Trong thời hạn 30 ngày kể từ ngày nhận đủ hồ sơ, Cục Hàng không '
          'Việt Nam thẩm định hồ sơ đăng ký cấp Giấy phép kinh doanh vận '
          'chuyển hàng không, báo cáo kết quả thẩm định lên Bộ trưởng Bộ Giao '
          'thông vận tải.\n'
          '2. Trong quá trình thẩm định, người nộp hồ sơ đề nghi cấp Giấy phép '
          'kinh doanh vận chuyển hàng không phải giải trình bổ sung về các vấn '
          'đề có liên quan theo yêu cầu của cơ quan thẩm định.',
  'treeId': 'chươngIII_điều12'},
 {'partId': '13',
  'partType': 'điều',
  'text': 'Điều 13. Quyết định cấp Giấy phép kinh doanh vận chuyển hàng không\n'
          '1. Trong thời hạn 15 ngày kể từ ngày nhận được báo cáo kết quả thẩm '
          'định của Cục Hàng không Việt Nam, Bộ trưởng Bộ Giao thông vận tải '
          'trình Thủ tướng Chính phủ quyết định hoặc yêu cầu Cục Hàng không '
          'Việt Nam thẩm định lại. Trình tự, thủ tục thẩm định lại áp dụng '
          'theo quy định tại Điều 12 Nghị định này.\n'
          '2. Trong thời hạn 15 ngày, kể từ ngày nhận được tờ trình của Bộ '
          'trưởng Bộ Giao thông vận tải, Thủ tướng Chính phủ xem xét việc cấp '
          'Giấy phép kinh doanh vận chuyển hàng không.\n'
          '3. Trong thời hạn 5 ngày làm việc kể từ ngày nhận được ý kiến cho '
          'phép của Thủ tướng Chính phủ, Bộ trưởng Bộ Giao thông vận tải cấp '
          'Giấy phép kinh doanh vận chuyển hàng không.\n'
          '4. Giấy phép kinh doanh vận chuyển hàng không bao gồm các nội dung '
          'sau đây:\n'
          'a) Tên doanh nghiệp, tên giao dịch; địa điểm trụ sở chính; chi '
          'nhánh, văn phòng đại diện;\n'
          'b) Số và ngày cấp của Giấy phép kinh doanh vận chuyển hàng không;\n'
          'c) Vốn điều lệ; loại hình doanh nghiệp; phần vốn góp của mỗi thành '
          'viên, cổ đông đối với công ty hợp danh, công ty trách nhiệm hữu '
          'hạn, công ty cổ phần;\n'
          'd) Phạm vi kinh doanh, loại hình vận chuyển hàng không.',
  'treeId': 'chươngIII_điều13'},
 {'partId': '14',
  'partType': 'điều',
  'text': 'Điều 14. Thẩm định và cấp Giấy phép kinh doanh hàng không chung\n'
          '1. Trong thời hạn 30 ngày kể từ ngày nhận đủ hồ sơ, Cục Hàng không '
          'Việt Nam thẩm định hồ sơ đăng ký cấp Giấy phép kinh doanh hàng '
          'không chung và ra quyết định về việc cấp giấy phép.\n'
          '2. Trong quá trình thẩm định, người nộp hồ sơ đề nghị cấp Giấy phép '
          'kinh doanh hàng không chung phải giải trình về các vẩn đề có liên '
          'quan theo yêu cầu của cơ quan thẩm định.\n'
          '3. Giấy phép kinh doanh hàng không chung bao gồm các nội dung sau '
          'đây:\n'
          'a) Tên doanh nghiệp, tên giao dịch; địa điểm trụ sở chính; chi '
          'nhánh, văn phòng đại diện;\n'
          'b) Số và ngày cấp của Giấy phép kinh doanh hàng không chung;\n'
          'c) Vốn điều lệ; loại hình doanh nghiệp; phần vốn góp của mỗi thành '
          'viên, cổ đông đối với công ty hợp danh, công ty trách nhiệm hữu '
          'hạn, công ty cổ phần;\n'
          'd) Phạm vi kinh doanh, loại hình hoạt động hàng không chung.',
  'treeId': 'chươngIII_điều14'},
 {'partId': '15',
  'partType': 'điều',
  'text': 'Điều 15. Thông báo việc cấp hoặc từ chối cấp Giấy phép kinh doanh '
          'vận chuyển hàng không, Giấy phép kinh doanh hàng không chung\n'
          'Cục Hàng không Việt Nam có trách nhiệm:\n'
          '1. Gửi Giấy phép kinh doanh vận chuyển hàng không, Giấy phép kinh '
          'doanh hàng không chung cho doanh nghiệp đề nghị cấp giấy phép trong '
          'thời hạn 3 ngày làm việc kể từ ngày nhận được giấy phép, ngày cấp '
          'giấy phép.\n'
          '2. Thông báo bằng văn bản về việc từ chối cấp giấy phép cho người '
          'nộp hồ sơ trong thời hạn 3 ngày làm việc kể từ ngày nhận được quyết '
          'định từ chối cấp Giấy phép kinh doanh vận chuyển hàng không, ngày '
          'quyết định từ chối cấp Giấy phép kinh doanh hàng không chung.',
  'treeId': 'chươngIII_điều15'},
 {'partId': '16',
  'partType': 'điều',
  'text': 'Điều 16. Công bố nội dung Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung\n'
          '1. Trong thời hạn 30 ngày kể từ ngày được cấp Giấy phép kinh doanh '
          'vận chuyển hàng không, Giấy phép kinh doanh hàng không chung, doanh '
          'nghiệp phải đăng trên một trong các loại tờ báo viết Trung ương '
          'hoặc báo điện tử trong ba số liên tiếp các nội dung của giấy phép.\n'
          '2. Trong trường hợp nội dung Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung thay đổi, doanh nghiệp '
          'phải công bố nội dung những thay đổi đó trong thời hạn và theo '
          'phương thức quy định tại khoản 1 của Điều này.',
  'treeId': 'chươngIII_điều16'},
 {'partId': '17',
  'partType': 'điều',
  'text': 'Điều 17. Huỷ bỏ Giấy phép kinh doanh vận chuyển hàng không, Giấy '
          'phép kinh doanh hàng không chung\n'
          '1. Giấy phép kinh doanh vận chuyển hàng không, Giấy phép kinh doanh '
          'hàng không chung bị huỷ bỏ trong các trường hợp sau đây:\n'
          'a) Không còn đáp ứng đủ điều kiện cấp giấy phép;\n'
          'b) Cố ý làm sai lệch thông tin trong hồ sơ xin cấp giấy phép;\n'
          'c) Không bắt đầu khai thác vận chuyển hàng không, hoạt động hàng '
          'không chung trong thời hạn 24 tháng, kể từ ngày được cấp giấy '
          'phép;\n'
          'd) Ngừng khai thác vận chuyển hàng không, hoạt động hàng không '
          'chung 12 tháng liên tục;\n'
          'đ) Không được cấp Giấy chứng nhận người khai thác tàu bay trong '
          'thời hạn 24 tháng, kể từ ngày được cấp giấy phép; Giấy chứng nhận '
          'người khai thác tàu bay bị thu hồi, huỷ bỏ quá 12 tháng mà không '
          'được cấp lại;\n'
          'e) Hoạt động sai mục đích hoặc không đúng với nội dung ghi trong '
          'giấy phép;\n'
          'g) Cố ý vi phạm quy định tại Điều 16, 18 và Điều 19 của Nghị định '
          'này;\n'
          'h) Vi phạm nghiêm trọng các quy định của pháp luật về an ninh quốc '
          'phòng, an ninh hàng không, an toàn hàng không, khai thác vận chuyển '
          'hàng không, hoạt động hàng không chung;\n'
          'i) Phá sản, giải thể doanh nghiệp.\n'
          '2. Trong trường hợp Giấy phép kinh doanh vận chuyển hàng không, '
          'Giấy phép kinh doanh hàng không chung bị huỷ bỏ, doanh nghiệp phải '
          'đình chỉ ngay việc kinh doanh vận chuyển hàng không, kinh doanh '
          'hàng không chung và có trách nhiệm giải quyết các hợp đồng vận '
          'chuyển, hợp đồng cung cấp địch vụ hàng không chung đã ký trước khi '
          'giấy phép bị huỷ bỏ.',
  'treeId': 'chươngIII_điều17'},
 {'partId': '18',
  'partType': 'điều',
  'text': 'Điều 18. Những thay đổi đối với doanh nghiệp phải được chấp thuận\n'
          '1. Doanh nghiệp đã được cấp Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung khi có những thay đổi '
          'sau đây phải làm thủ tục đề nghị chấp thuận:\n'
          'a) Bán doanh nghiệp; doanh nghiệp bị chia, bị hợp nhất, bị sáp '
          'nhập;\n'
          'b) Có những thay đổi khác với nội dung trong Giấy phép kinh doanh '
          'vận chuyển hàng không, Giấy phép kinh doanh hàng không chung quy '
          'định tương ứng tại khoản 4 Điều 13, khoản 3 Điều 14.\n'
          '2. Doanh nghiệp đã được cấp Giấy phép kinh doanh vận chuyển hàng '
          'không, Giấy phép kinh doanh hàng không chung phải gửi hồ sơ đề nghị '
          'thay đổi nội dung quy định tại khoản 1 Điều này đến Cục Hàng không '
          'Việt Nam để thẩm định.\n'
          '3. Thủ tục thẩm định hồ sơ, báo cáo kết quả thẩm định theo quy định '
          'tại Điều 12, 14 Nghị định này.\n'
          '4. Trong thời hạn 7 ngày làm việc kể từ ngày nhận được báo cáo thẩm '

Tách Điểm + Gộp text Khoản

In [4]:
def collect_all_text(node):
    """Hàm đệ quy gom toàn bộ text của node hiện tại và tất cả các node con."""
    texts = []
    
    # Lấy text của node nếu có
    node_text = node.get("text", "").strip()
    if node_text:
        texts.append(node_text)
    
    # Đệ quy xuống các node con (khoản, điểm,...)
    for child in node.get("children", []):
        child_text = collect_all_text(child)
        if child_text:
            texts.append(child_text)
            
    return "\n".join(texts)


def get_list_dieu(nodes):
    if not nodes:
        return []

    result = []

    for node in nodes:
        if node.get("partType") == "điều":
            result.append({
                "partId": node.get("partId"),
                "partType": node.get("partType"),
                "treeId": node.get("treeId"),
                "text": collect_all_text(node)
            })
            continue
        result.extend(get_list_dieu(node.get("children", [])))

    return result

In [6]:
pprint(documents[111])

{'content': '**QUYẾT ĐỊNH**\n'
            '\n'
            '**Sửa đổi, bổ sung, bãi bỏ một số điều của Quy chế phối hợp quản '
            'lý cụm công nghiệp trên địa bàn tỉnh Quảng Bình ban hành kèm theo '
            'Quyết định số25/2015/QĐ-UBND ngày 22/7/2015 của UBND tỉnh Quảng '
            'Bình**\n'
            '\n'
            '![](file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_image001.gif)\n'
            '\n'
            '**UỶ BAN NHÂN DÂN TỈNH QUẢNG BÌNH**\n'
            '\n'
            '*Căn cứ Luật Tổ chức chính quyền địa phương ngày 19/6/2015;*\n'
            '\n'
            '*Căn cứ Luật Ban hành văn bản quy phạm pháp luật ngày '
            '22/6/2015;*\n'
            '\n'
            '*Căn cứ Nghị định số 34/2016/NĐ-CP ngày 14/5/2016 của Chính phủ '
            'quy định một số điều và biện pháp thi hành Luật Ban hành văn bản '
            'quy phạm pháp luật;*\n'
            '\n'
            '*Căn cứ Nghị định số 68/2017/NĐ-CP ngày 25/5/2017 của Chính phủ '
            'về quản lý, phát triển cụm công nghiệp;*\n'
            '\n'
            '*Căn cứ Thông tư số 15/2017/TT-BCT ngày 31/8/2017 của Bộ Công '
            'Thương quy định, hướng dẫn thực hiện một số nội dung của Nghị '
            'định số 68/2017/NĐ-CP ngày 25/5/2017 của Chính phủ về quản lý, '
            'phát triển cụm công nghiệp;*\n'
            '\n'
            '*Theo đề nghị của Giám đốc Sở Công Thương tại Tờ trình số '
            '446/TTr-SCT ngày 26/4/2018**.*\n'
            '\n'
            '**QUYẾT ĐỊNH:**\n'
            '\n'
            '**Điều 1.**Sửa đổi, bổ sung một số điều của Quy chế phối hợp quản '
            'lý cụm công nghiệp trên địa bàn tỉnh Quảng Bình ban hành kèm theo '
            'Quyết định số 25/2015/QĐ-UBND ngày 22/7/2015 của UBND tỉnh Quảng '
            'Bìnhnhư sau:\n'
            '\n'
            '***1. Sửa đổi, bổ sung Khoản 1, Khoản 3 và Khoản 5 Điều 5 như '
            'sau:***\n'
            '\n'
            '“1. Là cơ quan đầu mối quản lý nhà nước đối với CCN trên địa bàn; '
            'chủ trì, phối hợp với các sở, ngành, UBND cấp huyện, lập, thẩm '
            'định quy hoạch phát triển CCN và thẩm định hồ sơ điều chỉnh, bổ '
            'sung quy hoạch CCN trình UBND tỉnh phê duyệt sau khi có ý kiến '
            'thoả thuận của Bộ Công Thương.”\n'
            '\n'
            '“3. Tham mưu, đề xuất với UBND tỉnh ban hành và tổ chức thực hiện '
            'quy định, quy chế, các chính sách, chương trình hỗ trợ đầu tư hạ '
            'tầng kỹ thuật, dự toán kinh phí hoạt động phát triển CCN.”\n'
            '\n'
            '“5. Chủ trì, phối hợp với các sở, ngành, báo cáo UBND tỉnh quyết '
            'định lựa chọn chủ đầu tư xây dựng hạ tầng kỹ thuật CCN; tham gia '
            'thẩm định quy hoạch chi tiết xây dựng, dự án đầu tư xây dựng hạ '
            'tầng kỹ thuật, báo cáo đánh giá tác động môi trườngCCN;phối hợp '
            'thẩm định chủ trương đầu tư dự án sản xuất kinh doanh trong CCN '
            'theo quy định, phân cấp của UBND tỉnh.”\n'
            '\n'
            '***2. Sửa đổi, bổ sung Khoản 2 và Khoản 3 Điều 6 như sau:***\n'
            '\n'
            '*“*2. Đầu mối tiếp nhận, giải quyết trình UBND tỉnh quyết định '
            'chủ trương đầu tư, cấp giấy chứng nhận đăng ký đầu tư các dự án '
            'xây dựng hạ tầng kỹ thuật, sản xuất kinh doanh trong CCN.*”*\n'
            '\n'
            '*“*3. Cấp mới, bổ sung, thay đổi, cấp lại và thu hồi Giấy chứng '
            'nhận đăng ký doanh nghiệp; Giấy chứng nhận đăng ký hoạt động chi '
            'nhánh, văn phòng đại diện thuộc thẩm quyền trong CCN, đồng thời '
            'quản lý hoạt động đầu tư trong nước và đầu tư trực tiếp nước '
            'ngoài trong CCN.”\n'
            '\n'
            '***3. Sửa đổi, bổ sung Khoản 1 và Khoản 2 Điều 9 như sau:***\n'
            '\n'
            '“1. Tiếp nhận, thực hiện các thủ tục để tham mưu, trình UBND tỉnh '
            'thu hồi đất, chuyển mục đích sử dụng đất, giao đất cho chủ đầu tư '
            'để xây dựng kết cấu hạ tầng; cho thuê đất và cấp Giấy chứng nhận '
            'quyền sử dụng đất, quyền sở hữu nhà ở (CCN làng nghề) và tài sản '
            'khác gắn liền với đất cho các tổ chức có dự án đầu tư vào CCN '
            'thuê đất của Nhà nước.”\n'
            '\n'
            '“2. Tổ chức thẩm định, trình cấp có thẩm quyền phê duyệt báo cáo '
            'đánh giá tác động môi trường, xác nhận kế hoạch bảo vệ môi '
            'trường, các quy định của pháp luật về bảo vệ môi trường và cấp '
            'phép khai thác, sử dụng tài nguyên nước và xả thải vào nguồn nước '
            'trong CCN.”\n'
            '\n'
            '***4. Sửa đổi, bổ sung Khoản 2 Điều 15 như sau:***\n'
            '\n'
            '“2. Phối hợp với cơ quan quản lý CCN, đơn vị kinh doanh hạ tầng '
            'hướng dẫn, tuyên truyền, giải quyết các vướng mắc về chính sách '
            'thuế đối với các doanh nghiệp trong CCN và tạo điều kiện thuận '
            'lợi cho doanh nghiệp trong việc thực hiện nộp thuế.”\n'
            '\n'
            '***5. Sửa đổi, bổ sung Khoản 5 và Khoản 6 Điều 18 như sau:***\n'
            '\n'
            '“5. Chủ trì, phối hợp với đơn vị được giao xây dựng hạ tầng kỹ '
            'thuật CCN lập hồ sơ thành lập, mở rộng, điều chỉnh, bổ sung quy '
            'hoạch phát triển CCN trên địa bàn gửi Sở Công Thương thẩm định '
            'trình UBND tỉnh quyết định.”\n'
            '\n'
            '“6. Chỉ đạo cơ quan, đơn vị chức năng lập quy hoạch chi tiết, dự '
            'án đầu tư xây dựng và tổ chức triển khai đầu tư xây dựng các CCN '
            'trên địa bàn sau khi được phê duyệt.”\n'
            '\n'
            '**Điều 2.** Bãi bỏ Khoản 4 Điều 5, Khoản 3 Điều 7, Điều 11, Khoản '
            '7 Điều 18 Quy chế phối hợp quản lý cụm công nghiệp trên địa bàn '
            'tỉnh Quảng Bình ban hành kèm theoQuyết định số 25/2015/QĐ-UBND '
            'ngày 22/7/2015 của UBND tỉnh Quảng Bình.\n'
            '\n'
            '**Điều 3.** Quyết định này có hiệu lực thi hành kể từ ngày05 / 6 '
            '/2018.\n'
            '\n'
            '**Điều 4**. Chánh Văn phòng UBND tỉnh, Giám đốc các Sở: Công '
            'Thương, Kế hoạch và Đầu tư, Tài chính, Xây dựng, Tài nguyên và '
            'Môi trường, Khoa học và Công nghệ, Giao thông Vận tải, Lao động - '
            'Thương binh và Xã hội; Cục trưởng Cục Thuế; Chủ tịch Liên đoàn '
            'Lao động tỉnh; Giám đốc: Bảo hiểm xã hội tỉnh, Công an tỉnh; Thủ '
            'trưởng các sở, ban, ngành cấp tỉnh; Chủ tịch UBND các huyện, thị '
            'xã, thành phố và các tổ chức, cá nhân có liên quan chịu trách '
            'nhiệm thi hành Quyết định này./.',
 'id': '129241',
 'list_dieu': [{'partId': '1',
                'partType': 'điều',
                'text': 'Điều 1.Sửa đổi, bổ sung một số điều của Quy chế phối '
                        'hợp quản lý cụm công nghiệp trên địa bàn tỉnh Quảng '
                        'Bình ban hành kèm theo Quyết định số 25/2015/QĐ-UBND '
                        'ngày 22/7/2015 của UBND tỉnh Quảng Bìnhnhư sau:\n'
                        '1. Sửa đổi, bổ sung Khoản 1, Khoản 3 và Khoản 5 Điều '
                        '5 như sau:\n'
                        '"1. Là cơ quan đầu mối quản lý nhà nước đối với CCN '
                        'trên địa bàn; chủ trì, phối hợp với các sở, ngành, '
                        'UBND cấp huyện, lập, thẩm định quy hoạch phát triển '
                        'CCN và thẩm định hồ sơ điều chỉnh, bổ sung quy hoạch '
                        'CCN trình UBND tỉnh phê duyệt sau khi có ý kiến thoả '
                        'thuận của Bộ Công Thương."\n'
                        '"3. Tham mưu, đề xuất với UBND tỉnh ban hành và tổ '
                        'chức thực hiện quy định, quy chế, các chính sách, '
                        'chương trình hỗ trợ đầu tư hạ tầng kỹ thuật, dự toán '
                        'kinh phí hoạt động phát triển CCN."\n'
                        '"5. Chủ trì, phối hợp với các sở, ngành, báo cáo UBND '
                        'tỉnh quyết định lựa chọn chủ đầu tư xây dựng hạ tầng '
                        'kỹ thuật CCN; tham gia thẩm định quy hoạch chi tiết '
                        'xây dựng, dự án đầu tư xây dựng hạ tầng kỹ thuật, báo '
                        'cáo đánh giá tác động môi trườngCCN;phối hợp thẩm '
                        'định chủ trương đầu tư dự án sản xuất kinh doanh '
                        'trong CCN theo quy định, phân cấp của UBND tỉnh."\n'
                        '2. Sửa đổi, bổ sung Khoản 2 và Khoản 3 Điều 6 như '
                        'sau:\n'
                        '"2. Đầu mối tiếp nhận, giải quyết trình UBND tỉnh '
                        'quyết định chủ trương đầu tư, cấp giấy chứng nhận '
                        'đăng ký đầu tư các dự án xây dựng hạ tầng kỹ thuật, '
                        'sản xuất kinh doanh trong CCN."\n'
                        '"3. Cấp mới, bổ sung, thay đổi, cấp lại và thu hồi '
                        'Giấy chứng nhận đăng ký doanh nghiệp; Giấy chứng nhận '
                        'đăng ký hoạt động chi nhánh, văn phòng đại diện thuộc '
                        'thẩm quyền trong CCN, đồng thời quản lý hoạt động đầu '
                        'tư trong nước và đầu tư trực tiếp nước ngoài trong '
                        'CCN."\n'
                        '3. Sửa đổi, bổ sung Khoản 1 và Khoản 2 Điều 9 như '
                        'sau:\n'
                        '"1. Tiếp nhận, thực hiện các thủ tục để tham mưu, '
                        'trình UBND tỉnh thu hồi đất, chuyển mục đích sử dụng '
                        'đất, giao đất cho chủ đầu tư để xây dựng kết cấu hạ '
                        'tầng; cho thuê đất và cấp Giấy chứng nhận quyền sử '
                        'dụng đất, quyền sở hữu nhà ở (CCN làng nghề) và tài '
                        'sản khác gắn liền với đất cho các tổ chức có dự án '
                        'đầu tư vào CCN thuê đất của Nhà nước."\n'
                        '"2. Tổ chức thẩm định, trình cấp có thẩm quyền phê '
                        'duyệt báo cáo đánh giá tác động môi trường, xác nhận '
                        'kế hoạch bảo vệ môi trường, các quy định của pháp '
                        'luật về bảo vệ môi trường và cấp phép khai thác, sử '
                        'dụng tài nguyên nước và xả thải vào nguồn nước trong '
                        'CCN."\n'
                        '4. Sửa đổi, bổ sung Khoản 2 Điều 15 như sau:\n'
                        '"2. Phối hợp với cơ quan quản lý CCN, đơn vị kinh '
                        'doanh hạ tầng hướng dẫn, tuyên truyền, giải quyết các '
                        'vướng mắc về chính sách thuế đối với các doanh nghiệp '
                        'trong CCN và tạo điều kiện thuận lợi cho doanh nghiệp '
                        'trong việc thực hiện nộp thuế."\n'
                        '5. Sửa đổi, bổ sung Khoản 5 và Khoản 6 Điều 18 như '
                        'sau:\n'
                        '"5. Chủ trì, phối hợp với đơn vị được giao xây dựng '
                        'hạ tầng kỹ thuật CCN lập hồ sơ thành lập, mở rộng, '
                        'điều chỉnh, bổ sung quy hoạch phát triển CCN trên địa '
                        'bàn gửi Sở Công Thương thẩm định trình UBND tỉnh '
                        'quyết định."\n'
                        '"6. Chỉ đạo cơ quan, đơn vị chức năng lập quy hoạch '
                        'chi tiết, dự án đầu tư xây dựng và tổ chức triển khai '
                        'đầu tư xây dựng các CCN trên địa bàn sau khi được phê '
                        'duyệt."',
                'treeId': 'điều1'},
               {'partId': '2',
                'partType': 'điều',
                'text': 'Điều 2. Bãi bỏ Khoản 4 Điều 5, Khoản 3 Điều 7, Điều '
                        '11, Khoản 7 Điều 18 Quy chế phối hợp quản lý cụm công '
                        'nghiệp trên địa bàn tỉnh Quảng Bình ban hành kèm '
                        'theoQuyết định số 25/2015/QĐ-UBND ngày 22/7/2015 của '
                        'UBND tỉnh Quảng Bình.',
                'treeId': 'điều2'},
               {'partId': '3',
                'partType': 'điều',
                'text': 'Điều 3. Quyết định này có hiệu lực thi hành kể từ '
                        'ngày05 / 6 /2018.',
                'treeId': 'điều3'},
               {'partId': '4',
                'partType': 'điều',
                'text': 'Điều 4. Chánh Văn phòng UBND tỉnh, Giám đốc các Sở: '
                        'Công Thương, Kế hoạch và Đầu tư, Tài chính, Xây dựng, '
                        'Tài nguyên và Môi trường, Khoa học và Công nghệ, Giao '
                        'thông Vận tải, Lao động - Thương binh và Xã hội; Cục '
                        'trưởng Cục Thuế; Chủ tịch Liên đoàn Lao động tỉnh; '
                        'Giám đốc: Bảo hiểm xã hội tỉnh, Công an tỉnh; Thủ '
                        'trưởng các sở, ban, ngành cấp tỉnh; Chủ tịch UBND các '
                        'huyện, thị xã, thành phố và các tổ chức, cá nhân có '
                        'liên quan chịu trách nhiệm thi hành Quyết định này./.',
                'treeId': 'điều4'}],
 'ngay_ban_hanh': '24/05/2018',
 'ngay_co_hieu_luc': '05/06/2018',
 'ngay_dang_cong_bao': None,
 'ngay_het_hieu_luc': '15/10/2021',
 'pham_vi': 'Địa phương',
 'so_ky_hieu': '13/2018/QĐ-UBND',
 'tinh_trang_hieu_luc': 'Hết hiệu lực toàn bộ',
 'title': 'Quyết định số 13/2018/QĐ-UBND Sửa đổi, bổ sung, bãi bỏ một số điều '
          'của Quy chế phối hợp quản lý cụm công nghiệp trên địa bàn tỉnh '
          'Quảng Bình ban hành kèm theo Quyết định số25/2015/QĐ-UBND ngày '
          '22/7/2015 của UBND tỉnh Quảng Bình'}

Lọc văn bản có Phụ lục

In [4]:
def clean_appendix_from_list_dieu(list_dieu):
    """
    Hàm duyệt qua list_dieu, giữ lại chuỗi Điều tăng dần (1, 2, 3...).
    Ngay khi partId quay đầu về số nhỏ hơn hoặc bằng số trước đó (ví dụ 1, 2, 1...),
    toàn bộ phần phía sau sẽ bị cắt bỏ vì thuộc Phụ lục/Mục lục dính kèm.
    """
    cleaned_list = []
    last_seen_id = 0

    for dieu in list_dieu:
        part_id_raw = dieu.get("partId")
        
        try:
            current_id = int(part_id_raw)
        except (ValueError, TypeError):
            # Ngay khi gặp partId không phải số (ví dụ chuỗi bất thường), coi như kết thúc phần Điều chính
            break

        # Nếu partId hiện tại lớn hơn partId liền trước -> Hợp lệ (1, 2, 3...)
        if current_id > last_seen_id:
            cleaned_list.append(dieu)
            last_seen_id = current_id
        else:
            # Ngay khi quay về 1 hoặc nhỏ hơn/bằng last_seen_id -> Bắt đầu Phụ lục -> Dừng hẳn
            break

    return cleaned_list

In [5]:
modified_docs_count = 0

for doc in tqdm(documents, desc="Cleaning appendix from list_dieu"):
    original_list_dieu = doc.get("list_dieu", [])
    if not original_list_dieu:
        continue

    cleaned_list = clean_appendix_from_list_dieu(original_list_dieu)

    if len(cleaned_list) < len(original_list_dieu):
        modified_docs_count += 1

    doc["list_dieu"] = cleaned_list

print(f"Tổng số văn bản: {len(documents):,}")
print(f"Số văn bản đã loại bỏ thành công phần Phụ lục: {modified_docs_count:,}")

Cleaning appendix from list_dieu: 100%|██████████| 169906/169906 [00:00<00:00, 770874.69it/s]

Tổng số văn bản: 169,906
Số văn bản đã loại bỏ thành công phần Phụ lục: 4,109

In [6]:
output_path_v3 = "data/documents_merged_v3.jsonl"

with open(output_path_v3, "w", encoding="utf-8") as f:
    for document in tqdm(documents, desc="Dumping to documents_merged_v3.jsonl"):
        f.write(json.dumps(document, ensure_ascii=False) + "\n")

print(f"Đã lưu thành công dữ liệu vào: {output_path_v3}")

Dumping to documents_merged_v3.jsonl: 100%|██████████| 169906/169906 [00:22<00:00, 7576.49it/s]

Đã lưu thành công dữ liệu vào: data/documents_merged_v3.jsonl

In [7]:
import random

list_doc_null_dieu = []
count = 0
for doc in tqdm(documents):
    list_dieu = doc.get("list_dieu", [])
    if list_dieu == None or len(list_dieu) == 0:
        count += 1
        list_doc_null_dieu.append(doc)
print(f"Số văn bản không có list_dieu: {count}")

100%|██████████| 169906/169906 [00:00<00:00, 1750900.26it/s]

Số văn bản không có list_dieu: 43639

In [8]:
for doc in tqdm(list_doc_null_dieu):
    doc = parser(doc["content"])

100%|██████████| 43639/43639 [00:27<00:00, 1573.17it/s]

In [9]:
pprint(list_doc_null_dieu[0])

{'content': '',
 'id': '135139',
 'list_dieu': [],
 'ngay_ban_hanh': '24/04/2019',
 'ngay_co_hieu_luc': None,
 'ngay_dang_cong_bao': None,
 'ngay_het_hieu_luc': '01/01/2021',
 'pham_vi': 'Địa phương',
 'so_ky_hieu': '27/2019/QĐ-UBND',
 'tinh_trang_hieu_luc': 'Hết hiệu lực toàn bộ',
 'title': 'Quyết định số 27/2019/QĐ-UBND về việc ban hành Bảng giá các loại '
          'đất định kỳ 5 năm (2015-2019) trên địa bàn tỉnh Quảng Trị'}

# Embedding

In [5]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
    print("GPU count:", torch.cuda.device_count())

CUDA available: True
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
CUDA version: 13.0
GPU count: 1

In [8]:
from sentence_transformers import SentenceTransformer
import torch

model = SentenceTransformer("AITeamVN/Vietnamese_Embedding_v2", device="cuda" if torch.cuda.is_available() else "cpu")
model.max_seq_length = 2048
print("Device:", model.device)
print("Max seq length:", model.max_seq_length)

/home/minora/miniconda3/envs/python3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 391/391 [00:00<00:00, 3651.26it/s]

Device: cuda:0
Max seq length: 2048

EDA

In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

MAX_SEQ_LENGTH = 2048

tokenizer = model.tokenizer

print("Tokenizer:", tokenizer.name_or_path)
print("Model max length:", tokenizer.model_max_length)


token_lengths = []

for doc in tqdm(documents, desc="Counting tokens"):
    for dieu in (doc["list_dieu"]):
        text = dieu.get("text", "")
        tokens = tokenizer(
            text,
            add_special_tokens=True,
            truncation=False
        )["input_ids"]

        token_lengths.append({
            "doc_id": doc["id"],
            "dieu_id": dieu.get("partId"),
            "token_count": len(tokens),
            "text": text
        })

df_tokens = pd.DataFrame(token_lengths)

Tokenizer: AITeamVN/Vietnamese_Embedding_v2
Model max length: 2048

Counting tokens: 100%|██████████| 169906/169906 [08:17<00:00, 341.82it/s]

In [84]:
MAX_SEQ_LENGTH = 2048

# 1. BASIC STATISTICS

display(
    df_tokens["token_count"]
    .describe(percentiles=[0.50, 0.75, 0.90, 0.95, 0.99])
    .to_frame()
)

# 2. THRESHOLD ANALYSIS
total = len(df_tokens)

over_2048 = (df_tokens["token_count"] > MAX_SEQ_LENGTH).sum()
under_2048 = total - over_2048

print(f"Total Điều              : {total:,}")
print(f"<= {MAX_SEQ_LENGTH} tokens       : {under_2048:,} "
      f"({under_2048 / total * 100:.2f}%)")
print(f">  {MAX_SEQ_LENGTH} tokens       : {over_2048:,} "
      f"({over_2048 / total * 100:.2f}%)")

         token_count
count  790178.000000
mean      233.664117
std       314.820413
min         4.000000
50%       126.000000
75%       273.000000
90%       540.000000
95%       803.000000
99%      1550.000000
max      8060.000000

Total Điều              : 790,178
<= 2048 tokens       : 788,464 (99.78%)
>  2048 tokens       : 1,714 (0.22%)

In [90]:
max_dieu = df_tokens.loc[df_tokens["token_count"].idxmax()]

print("Document ID :", max_dieu["doc_id"])
print("Điều ID     :", max_dieu["dieu_id"])
print("Token count :", max_dieu["token_count"])

Document ID : 74790
Điều ID     : 5
Token count : 8060

In [91]:
bins = [0,256,512,1024,1536,2048,3072,4096,8192,float("inf")]
labels = ["0-256","257-512","513-1024","1025-1536","1537-2048","2049-3072","3073-4096","4097-8192",">8192"]

df_tokens["token_range"] = pd.cut(
    df_tokens["token_count"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

distribution = (
    df_tokens["token_range"]
    .value_counts(sort=False)
    .to_frame("num_dieu")
)

distribution["percentage"] = (
    distribution["num_dieu"] / total * 100
)

display(distribution)

             num_dieu  percentage
token_range
0-256          578872   73.258430
257-512        125454   15.876676
513-1024        61976    7.843296
1025-1536       15747    1.992842
1537-2048        6415    0.811842
2049-3072        1030    0.130350
3073-4096         399    0.050495
4097-8192         285    0.036068
>8192               0    0.000000

In [92]:
distribution_doc = (
    df_tokens.groupby("token_range")["doc_id"]
    .nunique()
    .to_frame("num_document")
)

total_documents = df_tokens["doc_id"].nunique()

distribution_doc["percentage"] = (
    distribution_doc["num_document"] / total_documents * 100
)

display(distribution_doc)

/tmp/ipykernel_6363/2118691076.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_tokens.groupby("token_range")["doc_id"]

             num_document  percentage
token_range
0-256              124587   98.669486
257-512             41898   33.182067
513-1024            28504   22.574386
1025-1536           11327    8.970673
1537-2048            5508    4.362185
2049-3072             966    0.765045
3073-4096             393    0.311245
4097-8192             285    0.225712
>8192                   0    0.000000

In [40]:
tokens_over_2048 = []

for idx, row in df_tokens[df_tokens["token_count"] > 2048].iterrows():
    tokens_over_2048.append({
        "doc_id": row["doc_id"],
        "dieu_id": row["dieu_id"],
        "token_count": row["token_count"]
    })
    # In ra màn hình từng bản ghi
    print(f"Doc ID: {row['doc_id']} | Điều ID: {row['dieu_id']} | Token count: {row['token_count']}")

print(f"\nTổng số Điều có token > 2048: {len(tokens_over_2048)}")

Doc ID: 130884 | Điều ID: 1 | Token count: 5415
Doc ID: 137780 | Điều ID: 1 | Token count: 2876
Doc ID: 128912 | Điều ID: 2 | Token count: 4429
Doc ID: 128899 | Điều ID: 1 | Token count: 3068
Doc ID: 126493 | Điều ID: 2 | Token count: 2239
Doc ID: 117300 | Điều ID: 3 | Token count: 7932
Doc ID: 125924 | Điều ID: 3 | Token count: 2256
Doc ID: 122961 | Điều ID: 1 | Token count: 4588
Doc ID: 118648 | Điều ID: 1 | Token count: 4566
Doc ID: 59746 | Điều ID: 1 | Token count: 3500
Doc ID: 71710 | Điều ID: 1 | Token count: 2778
Doc ID: 181692 | Điều ID: 1 | Token count: 4113
Doc ID: 184967 | Điều ID: 3 | Token count: 3020
Doc ID: 50398 | Điều ID: 1 | Token count: 4449
Doc ID: 78261 | Điều ID: 1 | Token count: 8002
Doc ID: 113140 | Điều ID: 4 | Token count: 2159
Doc ID: 40622 | Điều ID: 1 | Token count: 2658
Doc ID: 57565 | Điều ID: 1 | Token count: 2661
Doc ID: 101033 | Điều ID: 2 | Token count: 3411
Doc ID: 20838 | Điều ID: 4 | Token count: 2173
Doc ID: 106475 | Điều ID: 1 | Token count: 6159
Doc ID: 102666 | Điều ID: 2 | Token count: 5092
Doc ID: 116321 | Điều ID: 4 | Token count: 5006
Doc ID: 114856 | Điều ID: 2 | Token count: 5450
Doc ID: 82041 | Điều ID: 1 | Token count: 2125
Doc ID: 113787 | Điều ID: 2 | Token count: 4138
Doc ID: 51238 | Điều ID: 1 | Token count: 2740
Doc ID: 113231 | Điều ID: 1 | Token count: 2164
Doc ID: 103472 | Điều ID: 3 | Token count: 4334
Doc ID: 86578 | Điều ID: 1 | Token count: 6297
Doc ID: 139348 | Điều ID: 1 | Token count: 3221
Doc ID: 56360 | Điều ID: 1 | Token count: 2067
Doc ID: 88584 | Điều ID: 4 | Token count: 2196
Doc ID: 88584 | Điều ID: 5 | Token count: 7105
Doc ID: 20415 | Điều ID: 1 | Token count: 3721
Doc ID: 101009 | Điều ID: 1 | Token count: 3838
Doc ID: 11352 | Điều ID: 4 | Token count: 2133
Doc ID: 59845 | Điều ID: 2 | Token count: 5996
Doc ID: 92be55d0-80fb-11f1-8e63-d3e0ff497965 | Điều ID: 6 | Token count: 2375
Doc ID: 92be55d0-80fb-11f1-8e63-d3e0ff497965 | Điều ID: 7 | Token count: 2760
Doc ID: 106119 | Điều ID: 2 | Token count: 2468
Doc ID: 93119 | Điều ID: 2 | Token count: 3805
Doc ID: 101618 | Điều ID: 2 | Token count: 2722
Doc ID: 91290 | Điều ID: 1 | Token count: 3740
Doc ID: 45405 | Điều ID: 1 | Token count: 5942
Doc ID: 32449 | Điều ID: 1 | Token count: 3809
Doc ID: 158570 | Điều ID: 3 | Token count: 2769
Doc ID: 71191 | Điều ID: 3 | Token count: 2211
Doc ID: 111940 | Điều ID: 1 | Token count: 3428
Doc ID: 57118 | Điều ID: 4 | Token count: 2068
Doc ID: 118512 | Điều ID: 1 | Token count: 2905
Doc ID: 156342 | Điều ID: 2 | Token count: 2594
Doc ID: 100821 | Điều ID: 1 | Token count: 2306
Doc ID: 74718 | Điều ID: 1 | Token count: 3605
Doc ID: 164863 | Điều ID: 2 | Token count: 4166
Doc ID: 101472 | Điều ID: 2 | Token count: 2864
Doc ID: 119816 | Điều ID: 1 | Token count: 6590
Doc ID: 52569 | Điều ID: 1 | Token count: 5570
Doc ID: 165149 | Điều ID: 2 | Token count: 7535
Doc ID: 176374 | Điều ID: 2 | Token count: 7566
Doc ID: 181668 | Điều ID: 2 | Token count: 2459
Doc ID: 66927 | Điều ID: 1 | Token count: 2630
Doc ID: 132190 | Điều ID: 1 | Token count: 3519
Doc ID: 10541 | Điều ID: 5 | Token count: 2413
Doc ID: 175166 | Điều ID: 18 | Token count: 2650
Doc ID: 27666 | Điều ID: 1 | Token count: 3230
Doc ID: 93346 | Điều ID: 2 | Token count: 4536
Doc ID: 76478 | Điều ID: 1 | Token count: 4554
Doc ID: 70706 | Điều ID: 3 | Token count: 2461
Doc ID: 33951580-6c83-11f1-a02c-653c91943882 | Điều ID: 5 | Token count: 2511
Doc ID: 45535 | Điều ID: 3 | Token count: 3162
Doc ID: 27498 | Điều ID: 3 | Token count: 3606
Doc ID: 175164 | Điều ID: 5 | Token count: 2467
Doc ID: 80917 | Điều ID: 1 | Token count: 2974
Doc ID: 180347 | Điều ID: 2 | Token count: 2165
Doc ID: 120632 | Điều ID: 1 | Token count: 3880
Doc ID: 92934 | Điều ID: 2 | Token count: 2111
Doc ID: 25714 | Điều ID: 2 | Token count: 3296
Doc ID: 39730 | Điều ID: 1 | Token count: 2759
Doc ID: 39730 | Điều ID: 2 | Token count: 4228
Doc ID: 141444 | Điều ID: 1 | Token count: 6203
Doc ID: 83964 | Điều ID: 1 | Token count: 4102
Doc ID: 83120 | Điều ID: 1 | Token count: 2763
Doc ID: 121374 | Điều ID: 1 | Token count: 2487
Doc ID: 61255 | Điều ID: 1 | Token count: 2353
Doc ID: 88504 | Điều ID: 1 | Token count: 3550
Doc ID: 61329 | Điều ID: 1 | Token count: 7344
Doc ID: 91649 | Điều ID: 1 | Token count: 6598
Doc ID: 48296 | Điều ID: 1 | Token count: 7656
Doc ID: 33796 | Điều ID: 1 | Token count: 4365
Doc ID: 91771 | Điều ID: 1 | Token count: 3979
Doc ID: 37715 | Điều ID: 1 | Token count: 2119
Doc ID: 36282 | Điều ID: 1 | Token count: 2676
Doc ID: 31545 | Điều ID: 1 | Token count: 2791
Doc ID: 87117 | Điều ID: 2 | Token count: 2801
Doc ID: 91745 | Điều ID: 1 | Token count: 2775
Doc ID: 91745 | Điều ID: 2 | Token count: 3210
Doc ID: 140944 | Điều ID: 13 | Token count: 4813
Doc ID: 84479 | Điều ID: 1 | Token count: 2156
Doc ID: 90663 | Điều ID: 1 | Token count: 2429
Doc ID: 42431 | Điều ID: 1 | Token count: 4735
Doc ID: 49492 | Điều ID: 1 | Token count: 3170
Doc ID: 90336 | Điều ID: 1 | Token count: 2302
Doc ID: 48064 | Điều ID: 1 | Token count: 2098
Doc ID: 63630 | Điều ID: 1 | Token count: 3197
Doc ID: 48497 | Điều ID: 1 | Token count: 4243
Doc ID: 124252 | Điều ID: 2 | Token count: 3843
Doc ID: 140196 | Điều ID: 3 | Token count: 2165
Doc ID: 117827 | Điều ID: 1 | Token count: 4954
Doc ID: 90446580-7460-11f1-a853-13d3025878ac | Điều ID: 3 | Token count: 2200
Doc ID: 77563 | Điều ID: 2 | Token count: 3274
Doc ID: 57543 | Điều ID: 1 | Token count: 4826
Doc ID: 62302 | Điều ID: 3 | Token count: 7043
Doc ID: 90590 | Điều ID: 1 | Token count: 3716
Doc ID: 73473 | Điều ID: 1 | Token count: 2552
Doc ID: 87436 | Điều ID: 1 | Token count: 2692
Doc ID: 154708 | Điều ID: 2 | Token count: 2260
Doc ID: 95099 | Điều ID: 2 | Token count: 2981
Doc ID: 73780 | Điều ID: 1 | Token count: 4923
Doc ID: 80853 | Điều ID: 1 | Token count: 4674
Doc ID: 145789 | Điều ID: 2 | Token count: 5987
Doc ID: 74391 | Điều ID: 2 | Token count: 2088
Doc ID: 114316 | Điều ID: 2 | Token count: 7310
Doc ID: 28359 | Điều ID: 1 | Token count: 4051
Doc ID: 68994 | Điều ID: 2 | Token count: 4733
Doc ID: 101177 | Điều ID: 1 | Token count: 5918
Doc ID: 80878 | Điều ID: 4 | Token count: 3082
Doc ID: 76756 | Điều ID: 1 | Token count: 2136
Doc ID: 65963 | Điều ID: 3 | Token count: 2485
Doc ID: 154551 | Điều ID: 2 | Token count: 4551
Doc ID: 58500 | Điều ID: 1 | Token count: 5195
Doc ID: 76932 | Điều ID: 1 | Token count: 3058
Doc ID: 20193 | Điều ID: 1 | Token count: 3746
Doc ID: 105940 | Điều ID: 1 | Token count: 4598
Doc ID: 175518 | Điều ID: 2 | Token count: 2975
Doc ID: 93321 | Điều ID: 2 | Token count: 2213
Doc ID: 93581 | Điều ID: 1 | Token count: 3604
Doc ID: 57332 | Điều ID: 1 | Token count: 2228
Doc ID: 148106 | Điều ID: 1 | Token count: 2953
Doc ID: 41803 | Điều ID: 1 | Token count: 2056
Doc ID: 4261 | Điều ID: 3 | Token count: 3452
Doc ID: 179226 | Điều ID: 2 | Token count: 7215
Doc ID: 82561 | Điều ID: 1 | Token count: 2101
Doc ID: 69400 | Điều ID: 1 | Token count: 3276
Doc ID: 95353 | Điều ID: 1 | Token count: 3446
Doc ID: 44028 | Điều ID: 1 | Token count: 4388
Doc ID: 95410 | Điều ID: 1 | Token count: 2826
Doc ID: 171401 | Điều ID: 3 | Token count: 2415
Doc ID: 124785 | Điều ID: 1 | Token count: 2761
Doc ID: 163172 | Điều ID: 1 | Token count: 2291
Doc ID: 74790 | Điều ID: 5 | Token count: 8060
Doc ID: 57017 | Điều ID: 5 | Token count: 4698
Doc ID: 71522 | Điều ID: 1 | Token count: 2999
Doc ID: 134369 | Điều ID: 1 | Token count: 5582
Doc ID: 46935 | Điều ID: 2 | Token count: 4859
Doc ID: 46935 | Điều ID: 5 | Token count: 2250
Doc ID: 12032 | Điều ID: 2 | Token count: 2239
Doc ID: 12713 | Điều ID: 2 | Token count: 2952
Doc ID: 168033 | Điều ID: 1 | Token count: 3357
Doc ID: 173113 | Điều ID: 1 | Token count: 3755
Doc ID: 21764 | Điều ID: 3 | Token count: 3970
Doc ID: 134202 | Điều ID: 2 | Token count: 3358
Doc ID: 7e253800-6c83-11f1-a546-399b42e56a78 | Điều ID: 5 | Token count: 5390
Doc ID: 156535 | Điều ID: 1 | Token count: 4829
Doc ID: 173366 | Điều ID: 1 | Token count: 2865
Doc ID: 179211 | Điều ID: 2 | Token count: 4614
Doc ID: 168088 | Điều ID: 1 | Token count: 5538
Doc ID: 12782 | Điều ID: 1 | Token count: 2959
Doc ID: 12782 | Điều ID: 2 | Token count: 4487
Doc ID: a2f074b0-54b4-11f1-a4b8-eda11642939f | Điều ID: 1 | Token count: 3638
Doc ID: 89763 | Điều ID: 1 | Token count: 2563
Doc ID: 110794 | Điều ID: 1 | Token count: 2147
Doc ID: 3f403810-80e7-11f1-92cf-f10f8a450679 | Điều ID: 11 | Token count: 3020
Doc ID: 68131 | Điều ID: 4 | Token count: 6627
Doc ID: 168279 | Điều ID: 17 | Token count: 2204
Doc ID: 10944 | Điều ID: 4 | Token count: 3323
Doc ID: 11351 | Điều ID: 4 | Token count: 5751
Doc ID: 89534 | Điều ID: 1 | Token count: 2181
Doc ID: 14227 | Điều ID: 2 | Token count: 2898
Doc ID: 27602 | Điều ID: 1 | Token count: 7216
Doc ID: 32588 | Điều ID: 5 | Token count: 3410
Doc ID: 32588 | Điều ID: 6 | Token count: 2789
Doc ID: 32588 | Điều ID: 7 | Token count: 2310
Doc ID: 29007 | Điều ID: 1 | Token count: 2507
Doc ID: 13745 | Điều ID: 1 | Token count: 2973
Doc ID: 13745 | Điều ID: 2 | Token count: 4395
Doc ID: 82451 | Điều ID: 1 | Token count: 2199
Doc ID: 105832 | Điều ID: 1 | Token count: 2928
Doc ID: 73819 | Điều ID: 3 | Token count: 3215
Doc ID: 13696 | Điều ID: 2 | Token count: 5262
Doc ID: 150365 | Điều ID: 1 | Token count: 2407
Doc ID: 184760 | Điều ID: 2 | Token count: 2661
Doc ID: 176822 | Điều ID: 2 | Token count: 2165
Doc ID: 172838 | Điều ID: 2 | Token count: 2308
Doc ID: bd5682e0-6f7b-11f1-937b-7fc043b1d195 | Điều ID: 7 | Token count: 2933
Doc ID: 33e66b90-6f7d-11f1-98e5-3fd4372d39c0 | Điều ID: 10 | Token count: 2050
Doc ID: 178686 | Điều ID: 1 | Token count: 2326
Doc ID: 76430 | Điều ID: 1 | Token count: 2192
Doc ID: 168962 | Điều ID: 4 | Token count: 2319
Doc ID: 174985 | Điều ID: 3 | Token count: 3200
Doc ID: 871f1e40-6ae3-11f1-8c74-938b26ae7f5b | Điều ID: 3 | Token count: 3424
Doc ID: 164315 | Điều ID: 1 | Token count: 2186
Doc ID: 167387 | Điều ID: 1 | Token count: 2449
Doc ID: 169023 | Điều ID: 2 | Token count: 3244
Doc ID: 162085 | Điều ID: 1 | Token count: 3565
Doc ID: 115360 | Điều ID: 2 | Token count: 4683
Doc ID: 165344 | Điều ID: 2 | Token count: 5550
Doc ID: 160877 | Điều ID: 2 | Token count: 5663
Doc ID: 157554 | Điều ID: 1 | Token count: 5821
Doc ID: 131857 | Điều ID: 1 | Token count: 2358
Doc ID: 182654 | Điều ID: 2 | Token count: 2236
Doc ID: 96139 | Điều ID: 1 | Token count: 2171
Doc ID: 147128 | Điều ID: 1 | Token count: 3913
Doc ID: 179362 | Điều ID: 2 | Token count: 2695
Doc ID: 140356 | Điều ID: 1 | Token count: 3190
Doc ID: 122879 | Điều ID: 1 | Token count: 2129
Doc ID: 103605 | Điều ID: 1 | Token count: 4247
Doc ID: 179526 | Điều ID: 3 | Token count: 3189
Doc ID: 179268 | Điều ID: 2 | Token count: 2594
Doc ID: 145427 | Điều ID: 4 | Token count: 5098
Doc ID: 136458 | Điều ID: 3 | Token count: 2220
Doc ID: 150415 | Điều ID: 1 | Token count: 2475
Doc ID: 130358 | Điều ID: 1 | Token count: 2678
Doc ID: 177076 | Điều ID: 1 | Token count: 2957
Doc ID: 134729 | Điều ID: 2 | Token count: 2543
Doc ID: 153584 | Điều ID: 1 | Token count: 2257
Doc ID: 136343 | Điều ID: 1 | Token count: 2835
Doc ID: 127610 | Điều ID: 2 | Token count: 3861
Doc ID: 182029 | Điều ID: 2 | Token count: 6974
Doc ID: 130878 | Điều ID: 2 | Token count: 2863
Doc ID: 147463 | Điều ID: 2 | Token count: 2296
Doc ID: c93e93d0-743b-11f1-99ea-512ccc105793 | Điều ID: 11 | Token count: 2142
Doc ID: 164987 | Điều ID: 1 | Token count: 3443
Doc ID: 84528 | Điều ID: 7 | Token count: 2520
Doc ID: 179415 | Điều ID: 7 | Token count: 3313
Doc ID: e2b458f0-8038-11f1-beae-a7a99fabf027 | Điều ID: 11 | Token count: 3165
Doc ID: 08ad9bb0-597f-11f1-a875-fb7e0a027ae6 | Điều ID: 5 | Token count: 4066
Doc ID: 170010 | Điều ID: 1 | Token count: 3498
Doc ID: 158684 | Điều ID: 1 | Token count: 3128
Doc ID: 26985 | Điều ID: 1 | Token count: 3943
Doc ID: 20576 | Điều ID: 1 | Token count: 2738
Doc ID: 179754 | Điều ID: 1 | Token count: 4758
Doc ID: 121103 | Điều ID: 1 | Token count: 5451
Doc ID: 5277dd10-662b-11f1-992a-9d39ff53c63f | Điều ID: 10 | Token count: 2169
Doc ID: 156209 | Điều ID: 2 | Token count: 4598
Doc ID: 117075 | Điều ID: 1 | Token count: 3509
Doc ID: 123030 | Điều ID: 1 | Token count: 2404
Doc ID: 152683 | Điều ID: 2 | Token count: 7514
Doc ID: 158214 | Điều ID: 5 | Token count: 4760
Doc ID: 113394 | Điều ID: 1 | Token count: 2864
Doc ID: 117809 | Điều ID: 1 | Token count: 3605
Doc ID: 186365 | Điều ID: 8 | Token count: 3254
Doc ID: 75155 | Điều ID: 1 | Token count: 2350
Doc ID: 87807 | Điều ID: 3 | Token count: 5332
Doc ID: 185547 | Điều ID: 9 | Token count: 2148
Doc ID: 99931 | Điều ID: 1 | Token count: 2354
Doc ID: 117715 | Điều ID: 1 | Token count: 6396
Doc ID: 78364 | Điều ID: 1 | Token count: 3054
Doc ID: 119963 | Điều ID: 2 | Token count: 2808
Doc ID: 95663 | Điều ID: 3 | Token count: 3336
Doc ID: 154882 | Điều ID: 1 | Token count: 2523
Doc ID: 152236 | Điều ID: 1 | Token count: 3408
Doc ID: 81128 | Điều ID: 1 | Token count: 3151
Doc ID: 119631 | Điều ID: 1 | Token count: 3089
Doc ID: 118281 | Điều ID: 2 | Token count: 3727
Doc ID: 92276 | Điều ID: 1 | Token count: 3839
Doc ID: 128290 | Điều ID: 1 | Token count: 2301
Doc ID: 55217 | Điều ID: 1 | Token count: 3237
Doc ID: 115687 | Điều ID: 1 | Token count: 3352
Doc ID: 178308 | Điều ID: 1 | Token count: 4605
Doc ID: 60192 | Điều ID: 1 | Token count: 2357
Doc ID: 179063 | Điều ID: 17 | Token count: 7188
Doc ID: 106057 | Điều ID: 1 | Token count: 2358
Doc ID: 184068 | Điều ID: 37 | Token count: 2617
Doc ID: 118794 | Điều ID: 1 | Token count: 2102
Doc ID: 74661 | Điều ID: 1 | Token count: 4714
Doc ID: 100253 | Điều ID: 1 | Token count: 3412
Doc ID: 119649 | Điều ID: 1 | Token count: 5214
Doc ID: 155158 | Điều ID: 2 | Token count: 3152
Doc ID: 63455 | Điều ID: 1 | Token count: 2852
Doc ID: 118280 | Điều ID: 1 | Token count: 2239
Doc ID: 98962 | Điều ID: 1 | Token count: 3369
Doc ID: 63139 | Điều ID: 1 | Token count: 2847
Doc ID: 127375 | Điều ID: 1 | Token count: 3541
Doc ID: 141640 | Điều ID: 2 | Token count: 2939
Doc ID: 139903 | Điều ID: 5 | Token count: 3566
Doc ID: 110818 | Điều ID: 18 | Token count: 2066
Doc ID: 127271 | Điều ID: 1 | Token count: 4175
Doc ID: 124411 | Điều ID: 1 | Token count: 3687
Doc ID: 111686 | Điều ID: 6 | Token count: 3997
Doc ID: 111686 | Điều ID: 12 | Token count: 2693
Doc ID: 139874 | Điều ID: 1 | Token count: 2540
Doc ID: 149688 | Điều ID: 4 | Token count: 2288
Doc ID: 86242 | Điều ID: 2 | Token count: 3753
Doc ID: 46346 | Điều ID: 3 | Token count: 5799
Doc ID: 117757 | Điều ID: 1 | Token count: 2336
Doc ID: 46375 | Điều ID: 5 | Token count: 2792
Doc ID: 122748 | Điều ID: 1 | Token count: 3110
Doc ID: 51406 | Điều ID: 1 | Token count: 2520
Doc ID: 54947 | Điều ID: 1 | Token count: 4155
Doc ID: 118121 | Điều ID: 1 | Token count: 5345
Doc ID: 138945 | Điều ID: 1 | Token count: 3382
Doc ID: 145835 | Điều ID: 1 | Token count: 3768
Doc ID: 148299 | Điều ID: 1 | Token count: 3649
Doc ID: 58381 | Điều ID: 1 | Token count: 2996
Doc ID: 32413 | Điều ID: 4 | Token count: 2289
Doc ID: 27062 | Điều ID: 25 | Token count: 7344
Doc ID: 53302 | Điều ID: 1 | Token count: 3222
Doc ID: 35900 | Điều ID: 1 | Token count: 5185
Doc ID: 46296 | Điều ID: 8 | Token count: 3131
Doc ID: 46296 | Điều ID: 10 | Token count: 3568
Doc ID: 52981 | Điều ID: 1 | Token count: 4845
Doc ID: 95887 | Điều ID: 1 | Token count: 2712
Doc ID: 160919 | Điều ID: 1 | Token count: 2391
Doc ID: 89227 | Điều ID: 1 | Token count: 2963
Doc ID: 75277 | Điều ID: 1 | Token count: 4235
Doc ID: 121361 | Điều ID: 8 | Token count: 2478
Doc ID: 73055 | Điều ID: 1 | Token count: 3457
Doc ID: 105539 | Điều ID: 1 | Token count: 2915
Doc ID: 52686 | Điều ID: 1 | Token count: 3234
Doc ID: 112173 | Điều ID: 4 | Token count: 6145
Doc ID: 37631 | Điều ID: 3 | Token count: 2498
Doc ID: 79485 | Điều ID: 1 | Token count: 2566
Doc ID: 28959 | Điều ID: 1 | Token count: 4582
Doc ID: 54331 | Điều ID: 2 | Token count: 6470
Doc ID: 54331 | Điều ID: 10 | Token count: 2987
Doc ID: 112551 | Điều ID: 1 | Token count: 2705
Doc ID: 30418 | Điều ID: 1 | Token count: 2193
Doc ID: 44772 | Điều ID: 1 | Token count: 6392
Doc ID: 61791 | Điều ID: 1 | Token count: 3534
Doc ID: 49890 | Điều ID: 1 | Token count: 5633
Doc ID: 43455 | Điều ID: 1 | Token count: 2137
Doc ID: 26479 | Điều ID: 1 | Token count: 2377
Doc ID: 83550 | Điều ID: 8 | Token count: 2062
Doc ID: 25151 | Điều ID: 4 | Token count: 2085
Doc ID: 26514 | Điều ID: 8 | Token count: 2260
Doc ID: 12168 | Điều ID: 11 | Token count: 3221
Doc ID: 12168 | Điều ID: 18 | Token count: 2416
Doc ID: 12168 | Điều ID: 44 | Token count: 3195
Doc ID: 12168 | Điều ID: 55 | Token count: 2151
Doc ID: 12168 | Điều ID: 100 | Token count: 5438
Doc ID: 12168 | Điều ID: 101 | Token count: 3263
Doc ID: 12168 | Điều ID: 112 | Token count: 5310
Doc ID: 12168 | Điều ID: 117 | Token count: 3127
Doc ID: 26673 | Điều ID: 3 | Token count: 2506
Doc ID: 125143 | Điều ID: 9 | Token count: 7884
Doc ID: 25349 | Điều ID: 3 | Token count: 2848
Doc ID: 27516 | Điều ID: 17 | Token count: 2153
Doc ID: 6544 | Điều ID: 3 | Token count: 3815
Doc ID: 12812 | Điều ID: 1 | Token count: 6280
Doc ID: 139085 | Điều ID: 1 | Token count: 3411
Doc ID: 15339 | Điều ID: 1 | Token count: 3510
Doc ID: 23746 | Điều ID: 1 | Token count: 3774
Doc ID: 4059 | Điều ID: 1 | Token count: 2824
Doc ID: 15417 | Điều ID: 2 | Token count: 2469
Doc ID: 15417 | Điều ID: 3 | Token count: 2464
Doc ID: 24259 | Điều ID: 1 | Token count: 5839
Doc ID: 1264 | Điều ID: 8 | Token count: 3268
Doc ID: 83336 | Điều ID: 1 | Token count: 2329
Doc ID: 22515 | Điều ID: 1 | Token count: 2731
Doc ID: 23428 | Điều ID: 1 | Token count: 3575
Doc ID: 18110 | Điều ID: 1 | Token count: 3256
Doc ID: 17311 | Điều ID: 3 | Token count: 4841
Doc ID: 33369 | Điều ID: 1 | Token count: 7470
Doc ID: 27957 | Điều ID: 1 | Token count: 4295
Doc ID: 143870 | Điều ID: 30 | Token count: 2422
Doc ID: 90a27d30-5b08-11f1-aee6-0d430505fd57 | Điều ID: 5 | Token count: 2117
Doc ID: 156007 | Điều ID: 1 | Token count: 2161
Doc ID: 171896 | Điều ID: 1 | Token count: 4315
Doc ID: 160297 | Điều ID: 1 | Token count: 2600
Doc ID: 148071 | Điều ID: 1 | Token count: 4143
Doc ID: 22500 | Điều ID: 3 | Token count: 5324
Doc ID: 157663 | Điều ID: 2 | Token count: 2922
Doc ID: 169136 | Điều ID: 1 | Token count: 3758
Doc ID: 142846 | Điều ID: 1 | Token count: 5745
Doc ID: 169441 | Điều ID: 1 | Token count: 2242
Doc ID: 67613 | Điều ID: 6 | Token count: 2734
Doc ID: 26382 | Điều ID: 3 | Token count: 2534
Doc ID: 86811 | Điều ID: 4 | Token count: 2691
Doc ID: 88469 | Điều ID: 1 | Token count: 2583
Doc ID: 84295 | Điều ID: 1 | Token count: 2395
Doc ID: 94029 | Điều ID: 2 | Token count: 2716
Doc ID: 12922 | Điều ID: 2 | Token count: 2584
Doc ID: 14038 | Điều ID: 1 | Token count: 2286
Doc ID: 26405 | Điều ID: 1 | Token count: 4124
Doc ID: 12520 | Điều ID: 1 | Token count: 3847
Doc ID: 32646 | Điều ID: 2 | Token count: 3792
Doc ID: 179178 | Điều ID: 33 | Token count: 2410
Doc ID: 12809 | Điều ID: 1 | Token count: 2634
Doc ID: 151943 | Điều ID: 12 | Token count: 2266
Doc ID: 26016 | Điều ID: 2 | Token count: 3466
Doc ID: 4f0c9ba0-4d1e-11f1-b3b5-1d57e972ca84 | Điều ID: 3 | Token count: 2412
Doc ID: 11612 | Điều ID: 2 | Token count: 3596
Doc ID: 25967 | Điều ID: 4 | Token count: 2279
Doc ID: 26497 | Điều ID: 1 | Token count: 5360
Doc ID: 155897 | Điều ID: 2 | Token count: 4770
Doc ID: 25949 | Điều ID: 2 | Token count: 3214
Doc ID: 25949 | Điều ID: 3 | Token count: 4076
Doc ID: 12789 | Điều ID: 2 | Token count: 3023
Doc ID: vbpqdinhchinh_331 | Điều ID: 1 | Token count: 2728
Doc ID: 25248 | Điều ID: 1 | Token count: 2459
Doc ID: 16518 | Điều ID: 1 | Token count: 2292
Doc ID: 15937 | Điều ID: 1 | Token count: 5962
Doc ID: 20577 | Điều ID: 51 | Token count: 5480
Doc ID: 149789 | Điều ID: 10 | Token count: 2257
Doc ID: 149789 | Điều ID: 11 | Token count: 2374
Doc ID: 95776 | Điều ID: 1 | Token count: 3069
Doc ID: 131410 | Điều ID: 1 | Token count: 2712
Doc ID: 83877 | Điều ID: 3 | Token count: 2401
Doc ID: 22100 | Điều ID: 4 | Token count: 3155

In [46]:
pprint(documents[0]["list_dieu"])

[{'partId': '1',
  'partType': 'điều',
  'text': 'Điều 1. Sửa đổi, bổ sung một số điều của Quy định điều kiện, tiêu '
          'chuẩn chức danh Trưởng, Phó các phòng chuyên môn, đơn vị thuộc Sở '
          'Tài nguyên và Môi trường; Trưởng, Phó phòng Tài nguyên và Môi '
          'trường thuộc Ủy ban nhân dân huyện, thành phố ban hành kèm theo '
          'Quyết định số 27/2016/QĐ-UBND ngày 07/9/2016 của Ủy ban nhân dân '
          'tỉnh Bắc Kạn:\n'
          '1. Khoản 6 Điều 4 được sửa đổi, bổ sung như sau:\n'
          '"6. Tuổi bổ nhiệm:\n'
          'a) Các chức vụ Trưởng phòng, Phó trưởng phòng chuyên môn, đơn vị '
          'thuộc Sở Tài nguyên và Môi trường, tuổi bổ nhiệm lần đầu không quá '
          '55 tuổi đối với nam và không quá 50 tuổi đối với nữ;\n'
          'b) Các chức vụ Trưởng phòng, Phó trưởng phòng Tài nguyên và Môi '
          'trường các huyện, thành phố, tuổi bổ nhiệm lần đầu không quá 45 '
          'tuổi (đối với cả nam và nữ);\n'
          'c) Trường hợp công chức, viên chức đã thôi giữ chức vụ lãnh đạo, '
          'sau một thời gian công tác nếu được xem xét để bổ nhiệm giữ chức vụ '
          'lãnh đạo, thì điều kiện về tuổi thực hiện như quy định khi bổ nhiệm '
          'lần đầu."\n'
          '2. Sửa đổi, bổ sung điểm e Điều 5 như sau:\n'
          '"e) Có trình độ lý luận chính trị cao cấp hoặc cử nhân."',
  'treeId': 'điều1'},
 {'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Chánh Văn phòng Ủy ban nhân dân tỉnh, Giám đốc Sở Nội vụ, '
          'Giám đốc Sở Tài nguyên và Môi trường, Chủ tịch Ủy ban nhân dân các '
          'huyện, thành phố, thủ trưởng các cơ quan, đơn vị có liên quan chịu '
          'trách nhiệm thi hành Quyết định này.',
  'treeId': 'điều2'},
 {'partId': '3',
  'partType': 'điều',
  'text': 'Điều 3. Quyết định này có hiệu lực từ ngày 10 tháng 12 năm 2018./.',
  'treeId': 'điều3'}]

Chunk điều > 2048 tokens

In [80]:
oversized_pairs = {(check["doc_id"], str(check["dieu_id"]))  for check in tokens_over_2048}

chunked_docs_count = 0

for doc in tqdm(documents, desc="Processing and chunking oversized Dieus"):
    doc_id = doc["id"]
    new_list_dieu = []
    has_chunked = False

    for dieu in doc.get("list_dieu", []):
        dieu_id = str(dieu.get("partId"))
        
        # Kiểm tra xem Điều này có nằm trong danh sách > 2048 tokens không
        if (doc_id, dieu_id) in oversized_pairs:
            # Chỉ chunk Điều bị oversized này
            chunked_khoans = chunker([dieu])
            new_list_dieu.extend(chunked_khoans)
            has_chunked = True
        else:
            # Giữ nguyên Điều hợp lệ
            new_list_dieu.append(dieu)
            
    if has_chunked:
        chunked_docs_count += 1
        
    doc["list_dieu"] = new_list_dieu

print(f"Tổng số văn bản: {len(documents):,}")
print(f"Số văn bản có Điều bị chunk nhỏ theo Khoản: {chunked_docs_count:,}")

Processing and chunking oversized Dieus: 100%|██████████| 169906/169906 [00:08<00:00, 19610.40it/s]

Tổng số văn bản: 169,906
Số văn bản có Điều bị chunk nhỏ theo Khoản: 8,322

In [81]:
with open("data/documents_merged_v4.jsonl", "w", encoding="utf-8") as f:
    for document in tqdm(documents, desc="Dumping to documents_merged_v4.jsonl"):
        f.write(json.dumps(document, ensure_ascii=False) + "\n")

Dumping to documents_merged_v4.jsonl: 100%|██████████| 169906/169906 [00:21<00:00, 7725.75it/s]

In [93]:
# Check doc với id cụ thể
test = []
for doc in documents:
    if doc["id"] == "74790":
        dieu_token_counts = df_tokens[df_tokens["doc_id"] == doc["id"]]["token_count"]
        total_tokens = dieu_token_counts.sum()
        print(f"Document ID: {doc['id']}, Total tokens: {total_tokens}")
        test = doc["list_dieu"]
        pprint(doc)
        break

Document ID: 74790, Total tokens: 8461
{'content': '|  |  |\n'
            '| --- | --- |\n'
            '| **ỦY BAN NHÂN DÂN**  **TỈNH LÂM ĐỒNG**  **\\*\\*\\***  **Số: '
            '34/2003/QĐ-UB** | **CỘNG HOÀ XÃ HỘI CHỦ NGHĨA VIỆT NAM**  **Độc '
            'lập - Tự do - Hạnh phúc**  '
            '--------------------------------------------  *Đà Lạt, ngày 05 '
            'tháng 03 năm 2003* |\n'
            '\n'
            '**QUYẾT ĐỊNH CỦA UBND TỈNH LÂM ĐỒNG**\n'
            '\n'
            '****V/v Ban hành bảng Quy định chỉ giới đường đỏ (lộ giới)****\n'
            '\n'
            '****các trục đường trên địa bàn thành phố Đà Lạt.****\n'
            '\n'
            '**ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG**\n'
            '\n'
            '- Căn cứ Luật Tổ chức Hội đồng Nhân dân và ủy ban Nhân dân (sửa '
            'đổi) ngày 21/6/1994;\n'
            '\n'
            '- Căn cứ Nghị định số 91/CP ngày 17/08/1994 của Chính phủ về việc '
            'ban hành Điều lệ quản lý quy hoạch đô thị;\n'
            '\n'
            '- Căn cứ Quyết định số 409/QĐ-TTg ngày 27/5/2002 của Thủ tướng '
            'Chính phủ phê duyệt Điều chỉnh Quy hoạch chung thành phố Đà Lạt, '
            'tỉnh Lâm Đồng và vùng phụ cận đến năm 2020;\n'
            '\n'
            '- Căn cứ Quyết định số 682/BXD-CSXD ngày 14/12/1996 của Bộ trưởng '
            'Bộ Xây Dựng về việc ban hành Quy chuẩn Xây dựng Việt Nam;\n'
            '\n'
            '- Căn cứ Nghị quyết số 28/NQ-HĐND.KVI ngày 30/01/2002 của Hội '
            'đồng Nhân dân tỉnh Lâm Đồng khoá VI, kỳ họp thứ 7 về đặt tên cho '
            'các đường chưa có tên và đổi tên đường có tên trùng lắp trên địa '
            'bàn Thành phố Đà Lạt;\n'
            '\n'
            '- Xét đề nghị của Giám đốc các Sở : Xây dựng, Giao thông Vận tải, '
            'Địa Chính và Chủ tịch ủy ban Nhân dân thành phố Đà Lạt,\n'
            '\n'
            '**QUYẾT ĐỊNH**\n'
            '\n'
            '**Điều l.**\n'
            '\n'
            '**1.1** Ban hành kèm theo Quyết định này bảng Quy định về chỉ '
            'giới đường đỏ (lộ giới) các trục đường trên địa bàn thành phố Đà '
            'Lạt.\n'
            '\n'
            '**1.2** Chỉ giới đường đỏ (lộ giới) : Chỉ giới đường đỏ là đường '
            'ranh giới được xác định trên bản đồ quy hoạch và thực địa để phân '
            'định ranh giới giữa phần đất để xây dựng công trình và phần đất '
            'được dành cho đường giao thông hoặc các công trình kỹ thuật hạ '
            'tầng, không gian công cộng khác. Trong đô thị, thường gặp lộ giới '
            'là chỉ giới đường đỏ của phần đất dành làm đường đô thị, bao gồm '
            'toàn bộ lòng đường, lề đường và vỉa hè.\n'
            '\n'
            '**1.3** Chỉ giới đường đỏ (lộ giới) là cơ sở pháp lý cho các cơ '
            'quan chức năng của Tỉnh, thành phố Đà Lạt thực hiện quản lý quy '
            'hoạch, xây dựng và nhà đất. Tất cả các cơ quan, đơn vị, cá nhân '
            'khi thực hiện các công tác có liên quan đến quy hoạch, xây dựng '
            'và nhà đất phải có trách nhiệm thực hiện.\n'
            '\n'
            '**Điều 2.** Quyết định này có hiệu lực thi hành kể từ ngày ký và '
            'thay thế Quyết định số 29/1999/QĐ-UB ngày 20/3/1999 và Quyết định '
            'số 09/2000/QĐ-UB ngày 14/01/2000 của ủy ban Nhân dân tỉnh Lâm '
            'Đồng. Các quy định trước đây trái với bảng Quy định ban hành kèm '
            'theo Quyết định này đều hết hiệu lực thi hành.\n'
            '\n'
            '**Điều 3.**\n'
            '\n'
            '**3.1** Giao ủy ban Nhân dân Thành phố Đà Lạt tổ chức phổ biến, '
            'niêm yết, công bố công khai bằng nhiều hình thức bảng Quy định '
            'ban hành kèm theo Quyết định này; lập hồ sơ và tổ chức cắm mốc '
            'chỉ giới đường đỏ dọc theo các tuyến đường để các tổ chức, đơn '
            'vị, cá nhân có liên quan biết thực hiện.\n'
            '\n'
            '**3.2** Giao Sở Tài chính Vật giá giải quyết kinh phí để ủy ban '
            'Nhân dân thành phố Đà Lạt tổ chức triển khai thực hiện việc cắm '
            'mốc chỉ giới đường đỏ.\n'
            '\n'
            '**3.3** Giao Sở Xây Dựng, Sở Địa Chính, Sở Giao Thông Vận Tải và '
            'các ngành chức năng có liên quan chịu trách nhiệm phối hợp với ủy '
            'ban Nhân dân thành phố Đà Lạt tổ chức thực hiện việc quản lý quy '
            'hoạch, xây dựng, nhà đất và xử lý các vi phạm.\n'
            '\n'
            '**Điều 4.** Xử lý đối với các công trình đã xây dựng vi phạm lộ '
            'giới :\n'
            '\n'
            '- Đối với các công trình gây nguy hại đến công trình giao thông '
            'hoặc công trình kỹ thuật hạ tầng, không gian công cộng khác hoặc '
            'gây mất an toàn cho hoạt động giao thông : Giao ủy ban Nhân dân '
            'thành phố Đà Lạt lập phương án để tổ chức giải tỏa ngay.\n'
            '\n'
            '- Đối với các công trình khác : Khi Nhà nước triển khai thực hiện '
            'theo quy hoạch hoặc dự án thì sẽ tổ chức giải tỏa.\n'
            '\n'
            'Khi triển khai giải tỏa, tùy vào điều kiện hồ sơ pháp lý của từng '
            'công trình, Nhà nước sẽ tính toán bồi thường thiệt hại theo các '
            'quy định hiện hành.\n'
            '\n'
            '**Điều 5.** Chánh Văn phòng Hội đồng Nhân dân và ủy ban Nhân dân '
            'Tỉnh, Giám đốc các Sở : Xây dựng; Địa chính; Giao thông Vận tải; '
            'Tài chính Vật giá; Công nghiệp; Nông nghiệp và Phát triển nông '
            'thôn; Tư pháp, Chủ tịch ủy ban Nhân dân thành phố Đà Lạt, Thủ '
            'trưởng các sở, ban, ngành, đơn vị và các cá nhân có liên quan '
            'chịu trách nhiệm thi hành quyết định này\n'
            '\n'
            'Trong quá trình thực hiện, có gì vướng mắc yêu cầu báo cáo ủy ban '
            'Nhân dân Tỉnh để xem xét giải quyết./-\n'
            '\n'
            '|  |  |\n'
            '| --- | --- |\n'
            '|  | **TM. ỦY BAN NHÂN DÂN TỈNH LÂM ĐỒNG**  **CHỦ TỊCH**  **(ĐÃ '
            'KÝ VÀ ĐÓNG DẤU)**  **PHAN THIÊN** |\n'
            '\n'
            '**BẢNG QUY ĐỊNH CHỈ GIỚI ĐƯỜNG ĐỎ (LỘ GIỚI) CÁC TRỤC ĐƯỜNG TRÊN '
            'ĐỊA BÀN THÀNH PHỐ ĐÀ LẠT**\n'
            '\n'
            '***(Ban hành kèm theo Quyết định số : 34/2003/QĐ-UB ngày 05 tháng '
            '3 năm 2003 của UBND tỉnh Lâm Đồng)***\n'
            '\n'
            '|  |  |  |  |  |  |  |  |\n'
            '| --- | --- | --- | --- | --- | --- | --- | --- |\n'
            '| STT | Tên đư\xadờng | Tên cũ | Điểm đầu | Điểm cuối | Chiều '
            'dài\xa0 (m) | Lộ giới (m) | Ghi chú |\n'
            '| 01 | An Bình | An Bình | Đống Đa | Triệu Việt Vương | 1.248 | '
            '16,0 |  |\n'
            '| 02 | An Dư\xadơng Vư\xadơng | An Dư\xadơng Vư\xadơng | Phan '
            'Đình Phùng | Cổ Loa | 550 | 14,0 |  |\n'
            '| 03 | An Tôn | An Tôn | Hoàng Văn Thụ | Cuối đ\xadường | 700 | '
            '16,0 |  |\n'
            '| 04 | An Sơn | An Sơn | Triệu Việt Vương | Y Dinh | 3.368 | 16,0 '
            '|  |\n'
            '| 05 | Ankroet | Ankroet | Xô Viết Nghệ Tĩnh | Suối Vàng - Đan '
            'Kia | 11.000 | 24,0 |  |\n'
            '| 06 | ánh Sáng | ánh Sáng | Lê Đại Hành | Nguyễn Văn Cừ | 325 | '
            '20,0 |  |\n'
            '| 07 | Ba Tháng Hai | Ba Tháng Hai | Khu Hòa Bình | Phan Đình '
            'Phùng | 860 | 14,0 đến 16,0 | Theo hiện trạng |\n'
            '|  |  |  | Phan Đình Phùng | Cầu Ba Tháng Hai |  | - | Theo quy '
            'hoạch chi tiết |\n'
            '|  |  |  | Cầu Ba Tháng Hai | Hoàng Văn Thụ |  | 20,0 |  |\n'
            '|  |  |  | Hoàng Văn Thụ | Pasteur |  | 20,0 | Theo quy hoạch chi '
            'tiết |\n'
            '| 08 | Ba Tháng Tư\xad | Ba Tháng Tư\xad | Hồ Tùng Mậu | Đống Đa '
            '| 800 | 27,0 |  |\n'
            '| 09 | Bạch Đằng | Bạch Đằng | Ngô Quyền | Nguyễn Siêu | 1.300 | '
            '16,0 |  |\n'
            '| 10 | Bà Huyện Thanh Quan | Bà Huyện Thanh Quan | Đinh Tiên '
            'Hoàng | Yersin | 3.260 | 20,0 | Theo quy hoạch chi tiết |\n'
            '| 11 | Bà Triệu | Bà Triệu | Cầu Bà Triệu | Trần Phú | 300 | 18,0 '
            '|  |\n'
            '| 12 | Bế Văn Đàn | - | Thái Phiên | Nguyễn Hữu Cầu | 580 | 10,0 '
            '|  |\n'
            '| 13 | Bùi Thị Xuân | Bùi Thị Xuân | Nguyễn Thái Học | Ngã 5 Đại '
            'học | 1.630 | 20,0 |  |\n'
            '| 14 | Cam Ly | Cam Ly | Hoàng Văn Thụ | Ankroet | 7.180 | 20,0 '
            '|  |\n'
            '| 15 | Cao Bá Quát | Cao Bá Quát | Phan Đình Phùng | Xô Viết Nghệ '
            'Tĩnh | 800 | 16,0 |  |\n'
            '| 16 | Cao Thắng | Cao Thắng | Ngô Quyền | Khu dân cư\xad số 3 | '
            '1.750 | 16,0 |  |\n'
            '| 17 | Cách Mạng Tháng Tám | - | Bà Huyện Thanh Quan | Cù Chính '
            'Lan | 3.020 | 16,0 |  |\n'
            '| 18 | Châu Văn Liêm | - | Thánh Mẫu (ngã 3 Nghĩa Trang) | Nguyễn '
            'Hoàng | 1.590 | 14,0 |  |\n'
            '| 19 | Chu Văn An | Chu Văn An | Trần Hư\xadng Đạo | Hồ Tùng Mậu '
            '| 350 | 14,0 | Theo quy hoạch chi tiết |\n'
            '| 20 | Cô Bắc | Cô Bắc | Quang Trung | Cô Giang | 350 | 14,0 |  '
            '|\n'
            '| 21 | Cô Giang | Cô Giang | Quang Trung | Quang Trung | 600 | '
            '14,0 |  |\n'
            '| 22 | Cổ Loa | Cổ Loa | An Dư\xadơng Vương | Thông Thiên Học | '
            '970 | 14,0 |  |\n'
            '| 23 | Công Chúa Ngọc Hân | - | Thánh Mẫu | Nguyễn Hoàng | 970 | '
            '14,0 |  |\n'
            '| 24 | Cù Chính Lan | - | Nguyên Tử Lực | Vòng Lâm Viên | 1.360 | '
            '16,0 |  |\n'
            '| 25 | Đa Minh | Đa Minh | Huyền Trân Công Chúa | Y Dinh | 600 | '
            '10,0 |  |\n'
            '| 26 | Đa Phú | Đa Phú | Ankroet (ngã 3 Kim Thạch) | Ankroet (ngã '
            '3 Hố Hồng) | 548 | 12,0 |  |\n'
            '| 27 | Đặng Thái Thân | Đặng Thái Thân | Ba Tháng Tư\xad (Cục Hải '
            'quan Đà Lạt) | Ba Tháng Tư\xad | 928 | 12,0 |  |\n'
            '| 28 | Đan Kia | Đan Kia | Xô Viết Nghệ Tĩnh | Cầu Ph\xadước '
            'Thành | 4.000 | 20,0 |  |\n'
            '| 29 | Dã Tượng | Dã Tư\xadợng | Lê Thánh Tôn | Hàn Thuyên | 500 '
            '| 16,0 |  |\n'
            '| 30 | Đào Duy Từ | Đào Duy Từ | Trần Phú | Suối Cát | 480 | 12,0 '
            '|  |\n'
            '| 31 | Đinh Công Tráng | Đinh Công Tráng | Bạch Đằng | Nguyễn '
            'Siêu | 780 | 14,0 |  |\n'
            '| 32 | Đinh Tiên Hoàng | Đinh Tiên Hoàng | Nguyễn Thái Học | Bùi '
            'Thị Xuân | 1.900 | 20,0 |  |\n'
            '| 33 | Đống Đa | Đống Đa | Ba Tháng Tư\xad | Cầu Đống Đa | 2.000 '
            '| 16,0 |  |\n'
            '| 34 | Đồng Tâm | Đồng Tâm | Hoàng Văn Thụ | Cuối đư\xadờng | 619 '
            '| 10,0 |  |\n'
            '| 35 | Đoàn Thị Điểm | Đoàn Thị Điểm | Bà Triệu | Trần Phú | 500 '
            '| 14,0 |  |\n'
            '| 36 | Gio An | Gio An | Hoàng Văn Thụ | Y Dinh | 500 | 10,0 |  '
            '|\n'
            '| 37 | Hai Bà Trưng | Hai Bà Trưng | Hải Th\xadượng | Ngô Quyền | '
            '2.850 | 20,0 |  |\n'
            '| 38 | Hà Huy Tập | Hà Huy Tập | Trần Phú | Lư\xadơng Thế Vinh | '
            '920 | 18,0 |  |\n'
            '|  |  |  | L\xadương Thế Vinh | Cầu Đống Đa |  | 16,0 |  |\n'
            '| 39 | Hàn Thuyên | Hàn Thuyên | Trần Bình Trọng | Yết Kiêu | '
            '1.300 | 16,0 |  |\n'
            '| 40 | Hải Thư\xadợng | Hải Th\xadượng | Ba Tháng Hai | Hai Bà '
            'Trư\xadng | 320 | - | Theo quy hoạch chi tiết |\n'
            '|  |  |  | Hai Bà Tr\xadưng | Trần Bình Trọng |  | 17,5 | Lệch '
            'tâm (trái : 10,0m; phải : 7,5m) |\n'
            '| 41 | Hồ Tùng Mậu | Hồ Tùng Mậu | Trần Phú | Nút giao thông Thủy '
            'Tạ | 1.300 | 16,0 |  |\n'
            '|  |  |  | Nút giao thông Thủy Tạ | Ba Tháng Tư\xad |  | 27,0 |  '
            '|\n'
            '| 42 | Hồ Xuân Hương | Hồ Xuân Hương | Phan Chu Trinh | Thái '
            'Phiên | 2.050 | 20,0 |  |\n'
            '| 43 | Hoàng Diệu | Hoàng Diệu | Hai Bà Tr\xadưng | Lê Lai | '
            '1.300 | 16,0 |  |\n'
            '| 44 | Hoàng Hoa Thám | Hoàng Hoa Thám | Hùng Vư\xadơng | Chùa '
            'Linh Phong | 1.500 | 14,0 |  |\n'
            '| 45 | Hoàng Văn Thụ | Hoàng Văn Thụ | Trần Phú | Cam Ly | 3.850 '
            '| 20,0 |  |\n'
            '| 46 | Hùng Vương | Hùng Vương | Trần H\xadưng Đạo | Nam Hồ | '
            '2.000 | 27,0 |  |\n'
            '| 47 | Huyền Trân Công Chúa | Huyền Trân Công Chúa | Hoàng Văn '
            'Thụ | Nghĩa trang Du Sinh | 1.650 | 16,0 |  |\n'
            '| 48 | Huỳnh Tấn Phát | - | Quốc lộ 20 (Xí nghiệp xây lắp Bư\xadu '
            'điện) | Cuối đư\xadờng | 2.070 | 10,0 |  |\n'
            '| 49 | Huỳnh Thúc Kháng | Huỳnh Thúc Kháng | Lê Hồng Phong | '
            'Pasteur | 550 | 14,0 |  |\n'
            '| 50 | Khe Sanh | Khe Sanh | Hùng Vư\xadơng | Bảo Quang Tự | '
            '1.438 | 27,0 | Lệch tâm (trái : 17,0m; phải : 10,0m) |\n'
            '|  |  |  | Bảo Quang Tự | Mimosa |  | 27,0 |  |\n'
            '| 51 | Khởi Nghĩa Bắc Sơn | Khởi Nghĩa Bắc Sơn | Ba tháng Tư\xad '
            '| Trần Hư\xadng Đạo | 1.000 | 16,0 |  |\n'
            '| 52 | Khu Chi Lăng | Khu Chi Lăng | - | - | 150 | - | Theo hiện '
            'trạng |\n'
            '| 53 | Khu Hòa Bình | Khu Hòa Bình | - | - | 520 | - | Theo quy '
            'hoạch chi tiết |\n'
            '| 54 | Kim Đồng | - | Ngô Quyền | Suối Cam Ly | 1.070 | 10,0 |  '
            '|\n'
            '| 55 | Kim Thạch | Kim Thạch | Ankroet | Trần Văn Côi | 760 | '
            '20,0 |  |\n'
            '| 56 | Ký Con | Ký Con | Nguyễn Du | Phó Đức Chính | 100 | 14,0 '
            '|  |\n'
            '| 57 | La Sơn Phu Tử | La Sơn Phu Tử | Phan Đình Phùng | Ngô '
            'Quyền | 270 | 20,0 |  |\n'
            '| 58 | Lâm Văn Thạnh | - | Quốc lộ 20 (khu vực khai thác đá của '
            'Học viện Lục Quân) | Quốc lộ 20 (UBND phư\xadờng 11) | 1.930 | '
            '14,0 |  |\n'
            '| 59 | Lê Hồng Phong | Lê Hồng Phong | Trần Phú | Triệu Việt '
            'Vương | 730 | 20,0 |  |\n'
            '| 60 | Lê Lai | Lê Lai | Trần Bình Trọng | Hoàng Diệu | 1.120 | '
            '16,0 |  |\n'
            '| 61 | Lê Đại Hành | Lê Đại Hành | Khu Hòa Bình | Phạm Ngũ Lão | '
            '800 | - | Theo quy hoạch chi tiết |\n'
            '|  |  |  | Phạm Ngũ Lão | Trần Phú |  | - | Theo quy hoạch chi '
            'tiết |\n'
            '| 62 | Lê Quý Đôn | Lê Quý Đôn | Ba Tháng Hai | Suối Phan Đình '
            'Phùng | 140 | 12,0 |  |\n'
            '| 63 | Lê Thánh Tôn | Lê Thánh Tôn | Nguyễn Thượng Hiền | Cuối '
            'đư\xadờng | 300 | 16,0 |  |\n'
            '| 64 | Lê Thị Hồng Gấm | Lê Thị Hồng Gấm | Nguyễn Thái Học | Phan '
            'Bội Châu | 500 | 20,0 |  |\n'
            '| 65 | Lê Thị Riêng | - | Xô Viết Nghệ Tĩnh (cổng Công ty cổ phần '
            'chăn nuôi) | Nguyễn Siêu | 890 | 10,0 |  |\n'
            '| 66 | Lê Văn Tám | - | Khởi Nghĩa Bắc Sơn | Trần Hư\xadng Đạo | '
            '541 | 10,0 |  |\n'
            '| 67 | Lữ Gia | Lữ Gia | Nguyễn Đình Chiểu | Cổng Học viện Lục '
            'Quân | 1.000 | 16,0 |  |\n'
            '|  |  |  | Lữ Gia | Cuối đư\xadờng |  | 14,0 | Đoạn còn lại |\n'
            '| 68 | Lư\xadơng Định Của | - | Quốc lộ 20 | Cuối đư\xadờng | '
            '1.260 | 10,0 |  |\n'
            '| 69 | Lư\xadơng Thế Vinh | - | Hà Huy Tập (ngang qua Trại giam) '
            '| Trư\xadờng Lê Quý Đôn | 355 | 16,0 |  |\n'
            '| 70 | Lý Nam Đế | - | Nguyễn Công Trứ | Phù Đổng Thiên Vư\xadơng '
            '(cổng KTX Đại học) | 1.170 | 14,0 |  |\n'
            '| 71 | Lý Thư\xadờng Kiệt | Lý Thư\xadờng Kiệt | Khu Chi Lăng | '
            'Nhà máy Atisô | 630 | 10,0 |  |\n'
            '| 72 | Lý Tự Trọng | Lý Tự Trọng | Bùi Thị Xuân | Khách sạn Đại '
            'Lợi | 1.272 | 14,0 |  |\n'
            '|  |  |  | Khách sạn Đại lợi | Lý Tự Trọng |  | 14,0 |  |\n'
            '| 73 | Ma Trang Sơn | Ma Trang Sơn | Hoàng Diệu | Hoàng Văn Thụ | '
            '1.000 | 10,0 |  |\n'
            '| 74 | Mẫu Tâm | Mẫu Tâm | Gio An | Huyền Trân Công Chúa | 900 | '
            '10,0 |  |\n'
            '| 75 | Mai Anh Đào | Vòng Lâm Viên | Phù Đổng Thiên Vương (ngã 3 '
            'Vạn Kiếp) | Nguyên Tử Lực | 1.490 | 24,0 |  |\n'
            '| 76 | Mai Hắc Đế | Mai Hắc Đế | Trần Bình Trọng | Ngô Quyền | '
            '200 | 16,0 |  |\n'
            '| 77 | Mai Xuân Th\xadưởng | - | Nguyên Tử Lực (ngã 4 Đập 1 Đa '
            'Thiện) | Vạn Hạnh | 610 | 14,0 |  |\n'
            '| 78 | Mạc Đỉnh Chi | Mạc Đỉnh Chi | Ba Tháng Hai | Hoàng Văn Thụ '
            '| 1.000 | 12,0 | Theo quy hoạch chi tiết |\n'
            '| 79 | Mê Linh | Mê Linh | Chi Lăng | Hồ Xuân Hương | 1.650 | '
            '18,0 |  |\n'
            '| 80 | Mimosa | Khe Sanh | Khe Sanh | Prenn | 9.857 | 27,0 |  |\n'
            '| 81 | Nam Hồ | Nam Hồ | Hùng Vư\xadơng | Hồ Xuân Hương | 1.550 | '
            '16,0 |  |\n'
            '| 82 | Nam Kỳ Khởi Nghĩa | Nam Kỳ Khởi Nghĩa | Ba Tháng Hai | Thủ '
            'Khoa Huân | 430 | 15,0 |  |\n'
            '| 83 | Ngô Gia Tự | - | Hồ Xuân Hương | Nghĩa trang Thái Phiên | '
            '1.650 | 24,0 |  |\n'
            '| 84 | Ngô Huy Diễn | - | Trần BìnhTrọng(ngang trường tiểu '
            'học\xa0\xa0\xa0\xa0 Trần Bình Trọng) | Ngã 3 Trần Bình Trọng - '
            'Hàn Thuyên | 380 | 10,0 |  |\n'
            '| 85 | Ngô Quyền | Ngô Quyền | Mai Hắc Đế | Bạch Đằng | 1.420 | '
            '16,0 |  |\n'
            '| 86 | Ngô Tất Tố | - | Mai Anh Đào | Trần Quang Khải (ngang qua '
            'nhà thờ Đa Thiện) | 1.170 | 14,0 |  |\n'
            '| 87 | Ngô Thì Nhậm | Đồng Tâm | Đồng Tâm | Ngô Thì Sỹ | 620 | '
            '10,0 |  |\n'
            '| 88 | Ngô Thì Sỹ | - | Pasteur | Huyền Trân Công Chúa | 1.080 | '
            '14,0 |  |\n'
            '| 89 | Ngô Văn Sở | Mê Linh | Khu Chi Lăng | Mê Linh | 1.040 | '
            '12,0 |  |\n'
            '| 90 | Nguyễn An Ninh | - | Ngô Quyền | Hàn Thuyên | 780 | 10,0 '
            '|  |\n'
            '| 91 | Nguyễn Chí Thanh | Nguyễn Chí Thanh | Khu Hòa Bình | '
            'Nguyễn Văn Cừ | 620 | 16,0 |  |\n'
            '| 92 | Nguyễn Công Trứ | Nguyễn Công Trứ | Ngã 5 Đại học | Xô '
            'Viết Nghệ Tĩnh | 1.100 | 20,0 | Lệch tâm (trái : 8,0m; phải : '
            '12,0m) |\n'
            '| 93 | Nguyễn Du | Nguyễn Du | Quang Trung | Trần Quý Cáp | 850 | '
            '16,0 |  |\n'
            '| 94 | Nguyễn Hoàng | - | Thánh Mẫu | Châu Văn Liêm | 2.050 | '
            '16,0 |  |\n'
            '| 95 | Nguyễn Hữu Cầu | - | Thái Phiên (gần chợ Thái Phiên) | '
            'Thái Phiên | 1.422 | 10,0 |  |\n'
            '| 96 | Nguyễn Hữu Cảnh | - | Phù Đổng Thiên Vương (Công ty may '
            'xuất khẩu) | Phù Đổng Thiên Vư\xadơng (gần ngã 3 Phù Đổng Thiên '
            'Vư\xadơng - Trần Quang Khải) | 603 | 12,0 |  |\n'
            '| 97 | Nguyễn Khuyến | Nguyễn Khuyến | Lê Lai | Cuối đ\xadường | '
            '110 | 16,0 |  |\n'
            '| 98 | Nguyễn Lương Bằng | - | Phan Đình Phùng | An Dư\xadơng '
            'Vương | 580 | 10,0 |  |\n'
            '| 99 | Nguyễn Đình Chiểu | Nguyễn Đình Chiểu | S\xadương Nguyệt '
            'Anh | Lữ Gia | 830 | 20,0 |  |\n'
            '| 100 | Nguyễn Đình Quân | Hoàng Văn Thụ | Hoàng Văn Thụ | Nghĩa '
            'trang Cam Ly | 1.080 | 16,0 |  |\n'
            '| 101 | Nguyên Phi ỷ Lan | - | Thánh Mẫu | Châu Văn Liêm | 720 | '
            '14,0 |  |\n'
            '| 102 | Nguyễn Siêu | Nguyễn Siêu | Xô Viết Nghệ Tĩnh | Cao Thắng '
            '| 630 | 20,0 |  |\n'
            '| 103 | Nguyễn Thái Bình | - | Ngô Gia Tự | Thái Phiên | 510 | '
            '10,0 |  |\n'
            '| 104 | Nguyễn Thái Học | Nguyễn Thái Học | Lê Đại Hành | Đinh '
            'Tiên Hoàng | 430 | 24,0 |  |\n'

Chunking

In [52]:
pprint(documents[0]["list_dieu"])

[{'partId': '1',
  'partType': 'điều',
  'text': 'Điều 1. Sửa đổi, bổ sung một số điều của Quy định điều kiện, tiêu '
          'chuẩn chức danh Trưởng, Phó các phòng chuyên môn, đơn vị thuộc Sở '
          'Tài nguyên và Môi trường; Trưởng, Phó phòng Tài nguyên và Môi '
          'trường thuộc Ủy ban nhân dân huyện, thành phố ban hành kèm theo '
          'Quyết định số 27/2016/QĐ-UBND ngày 07/9/2016 của Ủy ban nhân dân '
          'tỉnh Bắc Kạn:\n'
          '1. Khoản 6 Điều 4 được sửa đổi, bổ sung như sau:\n'
          '"6. Tuổi bổ nhiệm:\n'
          'a) Các chức vụ Trưởng phòng, Phó trưởng phòng chuyên môn, đơn vị '
          'thuộc Sở Tài nguyên và Môi trường, tuổi bổ nhiệm lần đầu không quá '
          '55 tuổi đối với nam và không quá 50 tuổi đối với nữ;\n'
          'b) Các chức vụ Trưởng phòng, Phó trưởng phòng Tài nguyên và Môi '
          'trường các huyện, thành phố, tuổi bổ nhiệm lần đầu không quá 45 '
          'tuổi (đối với cả nam và nữ);\n'
          'c) Trường hợp công chức, viên chức đã thôi giữ chức vụ lãnh đạo, '
          'sau một thời gian công tác nếu được xem xét để bổ nhiệm giữ chức vụ '
          'lãnh đạo, thì điều kiện về tuổi thực hiện như quy định khi bổ nhiệm '
          'lần đầu."\n'
          '2. Sửa đổi, bổ sung điểm e Điều 5 như sau:\n'
          '"e) Có trình độ lý luận chính trị cao cấp hoặc cử nhân."',
  'treeId': 'điều1'},
 {'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Chánh Văn phòng Ủy ban nhân dân tỉnh, Giám đốc Sở Nội vụ, '
          'Giám đốc Sở Tài nguyên và Môi trường, Chủ tịch Ủy ban nhân dân các '
          'huyện, thành phố, thủ trưởng các cơ quan, đơn vị có liên quan chịu '
          'trách nhiệm thi hành Quyết định này.',
  'treeId': 'điều2'},
 {'partId': '3',
  'partType': 'điều',
  'text': 'Điều 3. Quyết định này có hiệu lực từ ngày 10 tháng 12 năm 2018./.',
  'treeId': 'điều3'}]

In [33]:
def get_list_khoan(nodes):
    if not nodes:
        return []

    result = []

    for node in nodes:
        if node.get("partType") == "khoản":
            result.append({
                "partId": node.get("partId"),
                "partType": node.get("partType"),
                "treeId": node.get("treeId"),
                "text": collect_all_text(node)
            })
            continue
        result.extend(get_list_khoan(node.get("children", [])))

    return result

In [75]:
from dataclasses import asdict

def chunker(list_dieu):
    list_khoan = []
    
    for dieu in list_dieu:
        raw_text = dieu.get("text", "").strip()
        if not raw_text:
            continue
            
        # 1. Trích xuất dòng tiêu đề của Điều (Dòng đầu tiên, ví dụ: "Điều 1. Phạm vi điều chỉnh")
        dieu_lines = raw_text.split("\n")
        dieu_title = dieu_lines[0].strip()
        
        # 2. Parse lại văn bản Điều thành cấu trúc cây các Khoản
        parse_dieu = parser(raw_text)
        parse_dieu["content"]["parts"] = [asdict(part) for part in parse_dieu["content"]["parts"]]
        
        list_object_khoan = get_list_khoan(parse_dieu["content"]["parts"])
        
        # 3. Nếu Điều có các Khoản con, ghép dieu_title vào từng Khoản
        if list_object_khoan:
            for obj_khoan in list_object_khoan:
                text_khoan = obj_khoan.get("text", "").strip()
                
                # Ghép Tiêu đề Điều + Nội dung Khoản
                chunk_text = f"{dieu_title}\n{text_khoan}"
                
                dieu_chunk = {
                    "partId": dieu["partId"],
                    "partType": dieu["partType"],
                    "treeId": dieu["treeId"],
                    "khoanId": obj_khoan.get("partId"),  # (Tùy chọn) Lưu thêm ID của Khoản
                    "text": chunk_text
                }
                list_khoan.append(dieu_chunk)
        else:
            dieu_chunk = {
                "partId": dieu["partId"],
                "partType": dieu["partType"],
                "treeId": dieu["treeId"],
                "text": raw_text
            }
            list_khoan.append(dieu_chunk)
            
    return list_khoan

In [76]:
test_chunk = chunker(test)
pprint(test_chunk)

[{'khoanId': '1',
  'partId': '1',
  'partType': 'điều',
  'text': 'Điều 1. Vị trí và chức năng\n'
          '1. Sở Tài chính là cơ quan chuyên môn thuộc Ủy ban nhân dân tỉnh, '
          'thực hiện chức năng tham mưu, giúp Ủy ban nhân dân tỉnh quản lý nhà '
          'nước về quy hoạch; kế hoạch phát triển kinh tế - xã hội; tài chính; '
          'ngân sách nhà nước; kế hoạch đầu tư công; cơ chế, chính sách trong '
          'các lĩnh vực kinh tế, thu hút nguồn lực đầu tư, cơ cấu lại kinh tế, '
          'triển khai mô hình kinh tế mới, phương thức kinh doanh mới, thực '
          'hiện điều phối phát triển vùng, liên vùng; đầu tư trong nước, đầu '
          'tư nước ngoài ở địa phương; quản lý nguồn hỗ trợ phát triển chính '
          'thức (ODA), nguồn vốn vay ưu đãi của các nhà tài trợ và các nguồn '
          'viện trợ không hoàn lại không thuộc hỗ trợ phát triển chính thức '
          'của các cơ quan, tổ chức, cá nhân nước ngoài; nợ chính quyền địa '
          'phương, phí, lệ phí và thu khác của ngân sách nhà nước; tài sản '
          'công; các quỹ tài chính nhà nước ngoài ngân sách; đầu tư tài chính; '
          'tài chính doanh nghiệp; kế toán; kiểm toán độc lập; lĩnh vực giá và '
          'các hoạt động dịch vụ tài chính tại địa phương theo quy định của '
          'pháp luật; đấu thầu; đăng ký kinh doanh trong phạm vi địa phương; '
          'tổng hợp và thống nhất quản lý các vấn đề về doanh nghiệp, kinh tế '
          'tập thể, hợp tác xã, kinh tế tư nhân, hộ gia đình và tổ chức kinh '
          'tế khác; tổ chức cung ứng các dịch vụ công thuộc phạm vi quản lý '
          'nhà nước của Sở theo quy định của pháp luật.',
  'treeId': 'điều1'},
 {'khoanId': '2',
  'partId': '1',
  'partType': 'điều',
  'text': 'Điều 1. Vị trí và chức năng\n'
          '2. Sở Tài chính có tư cách pháp nhân, có con dấu và tài khoản '
          'riêng; chấp hành chỉ đạo, quản lý về tổ chức, biên chế và công tác '
          'của Ủy ban nhân dân tỉnh theo thẩm quyền; đồng thời chấp hành chỉ '
          'đạo, hướng dẫn, kiểm tra, thanh tra, về chuyên môn, nghiệp vụ của '
          'Bộ Tài chính.',
  'treeId': 'điều1'},
 {'khoanId': '1',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '1. Trình Ủy ban nhân dân tỉnh:\n'
          'a) Dự thảo quyết định của Ủy ban nhân dân tỉnh liên quan đến các '
          'lĩnh vực thuộc phạm vi quản lý của Sở Tài chính và các văn bản khác '
          'theo phân công của Ủy ban nhân dân tỉnh;\n'
          'b) Dự thảo các quyết định, kế hoạch phát triển, chương trình, biện '
          'pháp tổ chức thực hiện các nhiệm vụ về lĩnh vực tài chính - ngân '
          'sách, kế hoạch và đầu tư, các nhiệm vụ cải cách hành chính nhà nước '
          'thuộc lĩnh vực quản lý nhà nước của Sở theo quy định của pháp '
          'luật;\n'
          'c) Dự thảo quyết định việc phân cấp, ủy quyền nhiệm vụ quản lý nhà '
          'nước về lĩnh vực tài chính - ngân sách, quy hoạch, kế hoạch và đầu '
          'tư cho Sở Tài chính và Ủy ban nhân dân\xa0 cấp huyện;\n'
          'd) Dự thảo quyết định thành lập, tổ chức lại, giải thể các đơn vị '
          'sự nghiệp công lập thuộc Sở theo quy định của pháp luật;\n'
          'đ) Dự thảo quyết định quy định cụ thể chức năng, nhiệm vụ, quyền '
          'hạn và cơ cấu tổ chức của Sở;\n'
          'e) Dự thảo quyết định thực hiện xã hội hóa các hoạt động cung ứng '
          'dịch vụ sự nghiệp công theo ngành, lĩnh vực thuộc thẩm quyền của Ủy '
          'ban nhân dân\xa0 tỉnh và theo phân cấp của cơ quan nhà nước cấp '
          'trên (nếu có);\n'
          'g) Dự thảo kế hoạch thực hiện quy hoạch tỉnh; kế hoạch phát triển '
          'kinh tế - xã hội 5 năm và hàng năm của tỉnh, dự kiến kế hoạch đầu '
          'tư công 5 năm và hàng năm; kế hoạch xúc tiến đầu tư, chương trình '
          'xúc tiến đầu tư hằng năm, danh mục dự án thu hút đầu tư của địa '
          'phương; các cân đối chủ yếu về kinh tế - xã hội của tỉnh, trong đó '
          'có cân đối vốn đầu tư công; chương trình, kế hoạch thực hiện các '
          'mục tiêu phát triển bền vững, tăng trưởng xanh của tỉnh; kế hoạch '
          'và tình hình thực hiện các chương trình mục tiêu quốc gia; chương '
          'trình, biện pháp tổ chức thực hiện các nhiệm vụ cải cách hành chính '
          'nhà nước, cải thiện môi trường đầu tư kinh doanh trong lĩnh vực '
          'thuộc phạm vi quản lý nhà nước được giao;\n'
          'h) Dự thảo chương trình hành động thực hiện kế hoạch phát triển '
          'kinh tế - xã hội theo Nghị quyết của Hội đồng nhân dân tỉnh và chịu '
          'trách nhiệm theo dõi, tổng hợp tình hình thực hiện kế hoạch tháng, '
          'quý, 6 tháng, năm và 05 năm để báo cáo Ủy ban nhân dân cấp tỉnh '
          'điều hành, phối hợp việc thực hiện các cân đối chủ yếu về kinh tế - '
          'xã hội của tỉnh;\n'
          'i) Dự thảo chương trình, kế hoạch sắp xếp, đổi mới phát triển doanh '
          'nghiệp Nhà nước và doanh nghiệp có vốn góp của Nhà nước do địa '
          'phương quản lý; cơ chế quản lý đối với doanh nghiệp Nhà nước và '
          'doanh nghiệp có vốn góp của Nhà nước; dự thảo chương trình, kế '
          'hoạch, đề án hỗ trợ phát triển doanh nghiệp nhỏ và vừa, doanh '
          'nghiệp tư nhân (bao gồm chương trình đổi mới sáng tạo, khởi nghiệp '
          'sáng tạo), phát triển hợp tác xã, hộ kinh doanh hàng năm và 5 năm '
          'trên địa bàn tỉnh; dự thảo kế hoạch cải thiện chỉ số môi trường đầu '
          'tư kinh doanh và nâng cao năng lực cạnh tranh cấp tỉnh;\n'
          'k) Dự thảo văn bản chấp thuận chủ trương đầu tư, chấp thuận điều '
          'chỉnh chủ trương đầu tư, chấp thuận nhà đầu tư, chấp thuận chủ '
          'trương đầu tư đồng thời chấp thuận nhà đầu tư theo phân công của Ủy '
          'ban nhân dân tỉnh đối với các dự án thuộc thẩm quyền chấp thuận chủ '
          'trương đầu tư, chấp thuận nhà đầu tư của Ủy ban nhân dân tỉnh theo '
          'quy định pháp luật về đầu tư; dự thảo danh mục dự án đầu tư có sử '
          'dụng đất; dự thảo yêu cầu sơ bộ về năng lực, kinh nghiệm; phương án '
          'tổ chức thực hiện lựa chọn nhà đầu tư căn cứ kết quả đánh giá sơ bộ '
          'về năng lực, kinh nghiệm đối với dự án đầu tư có sử dụng đất.',
  'treeId': 'điều2'},
 {'khoanId': '2',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '2. Trình Chủ tịch Ủy ban nhân dân tỉnh:\n'
          'a) Dự thảo các văn bản thuộc thẩm quyền ban hành của Chủ tịch Ủy '
          'ban nhân dân tỉnh theo phân công về lĩnh vực quản lý nhà nước của '
          'Sở;\n'
          'b) Dự thảo quyết định quy định chức năng, nhiệm vụ, quyền hạn và cơ '
          'cấu tổ chức của các đơn vị sự nghiệp công lập thuộc Sở theo quy '
          'định của pháp luật.',
  'treeId': 'điều2'},
 {'khoanId': '3',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '3. Giúp Chủ tịch Ủy ban nhân dân tỉnh chỉ đạo, hướng dẫn, kiểm tra, '
          'thông tin, tuyên truyền, phổ biến giáo dục pháp luật về lĩnh vực '
          'thuộc phạm vi quản lý nhà nước được giao; tổ chức thực hiện các văn '
          'bản quy phạm pháp luật, các chính sách, quy hoạch, kế hoạch, chương '
          'trình, dự án, đề án, thuộc phạm vi quản lý nhà nước của Sở sau khi '
          'được cấp có thẩm quyền ban hành hoặc phê duyệt.',
  'treeId': 'điều2'},
 {'khoanId': '4',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '4. Về quy hoạch, kế hoạch\n'
          'a) Tham mưu, giúp Ủy ban nhân dân tỉnh ban hành và tổ chức thực '
          'hiện văn bản quy phạm pháp luật về quy hoạch tỉnh; kế hoạch, chính '
          'sách, giải pháp, bố trí nguồn lực thực hiện và đánh giá thực hiện '
          'quy hoạch tỉnh; tổ chức lấy ý kiến, tổ chức công bố quy hoạch tỉnh; '
          'cung cấp dữ liệu có liên quan thuộc phạm vi quản lý của địa phương '
          'để cập nhật vào hệ thống thông tin và cơ sở dữ liệu quốc gia về quy '
          'hoạch; rà soát, đề xuất chủ trương điều chỉnh quy hoạch tỉnh; báo '
          'cáo về hoạt động quy hoạch trên địa bàn tỉnh hằng năm; quản lý và '
          'điều hành một số lĩnh vực về thực hiện kế hoạch được Ủy ban nhân '
          'dân tỉnh giao;\n'
          'b) Xây dựng, đánh giá, quản lý, lưu trữ, công bố, cung cấp, khai '
          'thác và sử dụng thông tin, cơ sở dữ liệu về quy hoạch;\n'
          'c) Chủ trì, phối hợp với các Sở, ban, ngành, Ủy ban nhân dân cấp '
          'huyện đề xuất nội dung tích hợp vào quy hoạch cấp huyện, tỉnh; giám '
          'sát quá trình triển khai thực hiện quy hoạch, kế hoạch đã được cấp '
          'có thẩm quyền phê duyệt.',
  'treeId': 'điều2'},
 {'khoanId': '5',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '5. Về quản lý ngân sách nhà nước\n'
          'a) Xây dựng, tổng hợp, lập, trình Ủy ban nhân dân tỉnh để trình cấp '
          'có thẩm quyền kế hoạch tài chính 05 năm địa phương, kế hoạch tài '
          'chính - ngân sách nhà nước 03 năm; dự toán thu ngân sách nhà nước '
          'trên địa bàn, dự toán thu, chi ngân sách địa phương và phương án '
          'phân bổ ngân sách cấp tỉnh hàng năm; điều chỉnh kế hoạch tài chính '
          '05 năm địa phương, kế hoạch tài chính - ngân sách nhà nước 03 năm, '
          'dự toán ngân sách địa phương và phương án phân bổ ngân sách cấp '
          'tỉnh trong trường hợp cần thiết;\n'
          'b) Xây dựng, trình Ủy ban nhân dân tỉnh để trình cơ quan có thẩm '
          'quyền quyết định phương án bổ sung dự toán số tăng thu của ngân '
          'sách địa phương, phương án phân bổ, sử dụng số tăng thu và tiết '
          'kiệm chi của ngân sách địa phương và phương án điều chỉnh dự toán '
          'ngân sách địa phương theo quy định;\n'
          'c) Xây dựng, trình Ủy ban nhân dân tỉnh để trình cấp có thẩm quyền '
          'quy định phân cấp nguồn thu, nhiệm vụ chi, tỷ lệ phần trăm (%) phân '
          'chia giữa các cấp ngân sách ở địa phương đối với các khoản thu phân '
          'chia và mức bổ sung từ ngân sách cấp trên cho ngân sách cấp dưới '
          'theo quy định của Luật Ngân sách nhà nước;\n'
          'd) Trình Ủy ban nhân dân tỉnh để trình cấp có thẩm quyền quyết định '
          'sử dụng dự phòng ngân sách cấp tỉnh, sử dụng quỹ dự trữ tài chính '
          'của địa phương và các nguồn dự trữ tài chính khác theo quy định của '
          'pháp luật;\n'
          'đ) Chủ trì, phối hợp với các cơ quan có liên quan trong việc xây '
          'dựng, trình Ủy ban nhân dân tỉnh để trình cấp có thẩm quyền quy '
          'định các định mức phân bổ và các chế độ, tiêu chuẩn, định mức chi '
          'ngân sách của địa phương theo quy định của pháp luật về ngân sách '
          'nhà nước;\n'
          'e) Tham mưu, tổ chức thực hiện ngân sách địa phương, điều hành ngân '
          'sách địa phương theo thẩm quyền; theo dõi, đôn đốc việc tổ chức '
          'thực hiện dự toán ngân sách cấp tỉnh và cấp dưới;\n'
          'g) Kiểm tra việc phân bổ dự toán ngân sách được giao; hướng dẫn '
          'việc quản lý, điều hành ngân sách; chỉ đạo, kiểm tra việc thực hiện '
          'nhiệm vụ thu, chi ngân sách của các cơ quan, đơn vị cùng cấp và '
          'ngân sách của cấp dưới;\n'
          'h) Hướng dẫn việc hạch toán, quyết toán ngân sách địa phương và '
          'định kỳ báo cáo việc thực hiện dự toán thu, chi ngân sách và tổ '
          'chức thực hiện chế độ công khai tài chính ngân sách của nhà nước '
          'theo quy định của pháp luật;\n'
          'i) Tổng hợp, lập quyết toán ngân sách địa phương trình Ủy ban nhân '
          'dân tỉnh để trình cấp có thẩm quyền quyết toán ngân sách địa phương '
          'theo quy định của Luật Ngân sách nhà nước;\n'
          'k) Trình Ủy ban nhân dân tỉnh quyết định chi ứng trước, thu hồi các '
          'khoản chi ứng trước của ngân sách cấp tỉnh theo quy định của Luật '
          'Ngân sách nhà nước và các văn bản hướng dẫn thực hiện;\n'
          'l) Phối hợp với Kho bạc Nhà nước tỉnh lập báo cáo tài chính theo '
          'quy định của pháp luật.',
  'treeId': 'điều2'},
 {'khoanId': '6',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '6. Về quản lý vốn đầu tư phát triển\n'
          'a) Tham gia với các cơ quan liên quan về nội dung tài chính, các '
          'chính sách ưu đãi tài chính đối với các dự án;\n'
          'b) Kiểm tra tình hình thực hiện phân bổ, quản lý, sử dụng, thanh '
          'toán, quyết toán vốn đầu tư thuộc ngân sách địa phương của chủ đầu '
          'tư và cơ quan tài chính huyện, xã và vốn từ các nguồn thu hợp pháp '
          'khác của đơn vị sự nghiệp; tình hình kiểm soát, thanh toán vốn đầu '
          'tư của Kho bạc Nhà nước ở tỉnh, huyện;\n'
          'c) Chủ trì tổ chức thẩm tra quyết toán vốn đầu tư dự án hoàn thành '
          'trình người có thẩm quyền quyết định đầu tư phê duyệt đối với các '
          'dự án sử dụng vốn đầu tư công thuộc ngân sách do Ủy ban nhân dân '
          'tỉnh quản lý (trừ trường hợp Chủ tịch Ủy ban nhân dân tỉnh có quy '
          'định khác);\n'
          'd) Trình Ủy ban nhân dân tỉnh quy định trình tự, thời hạn lập, gửi, '
          'xét duyệt, thẩm định và ra thông báo thẩm định báo cáo quyết toán '
          'vốn đầu tư công nguồn ngân sách nhà nước; tổng hợp, báo cáo quyết '
          'toán vốn đầu tư công nguồn ngân sách nhà nước theo năm ngân sách do '
          'địa phương quản lý theo quy định;\n'
          'đ) Tổng hợp, phân tích, báo cáo tình hình huy động và sử dụng vốn '
          'đầu tư, đánh giá hiệu quả quản lý, sử dụng vốn đầu tư;\n'
          'e) Phối hợp với Kho bạc Nhà nước tỉnh theo dõi và đôn đốc các chủ '
          'đầu tư, đơn vị quản lý dự án thu hồi số vốn đã thanh toán thừa khi '
          'dự án hoàn thành được phê duyệt quyết toán có số vốn được quyết '
          'toán thấp hơn số vốn đã thanh toán cho dự án và đôn đốc thu hồi các '
          'khoản tạm ứng vốn đầu tư xây dựng cơ bản quá hạn chưa thu hồi.',
  'treeId': 'điều2'},
 {'khoanId': '7',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '7. Về đầu tư phát triển, đầu tư theo phương thức đối tác công tư\n'
          'a) Chủ trì, phối hợp với các cơ quan liên quan xây dựng kế hoạch và '
          'dự kiến bố trí mức vốn đầu tư công cho từng nhiệm vụ, chương trình, '
          'dự án sử dụng nguồn vốn đầu tư công do tỉnh quản lý;\n'
          'b) Chủ trì, phối hợp với các cơ quan liên quan xây dựng, tổ chức '
          'thực hiện, theo dõi, giám sát việc thực hiện chính sách và quy định '
          'của pháp luật về đầu tư công, pháp luật về đầu tư theo phương thức '
          'đối tác công tư, việc tuân thủ kế hoạch đầu tư công;\n'
          'c) Chủ trì, phối hợp với các cơ quan có liên quan thực hiện giám '
          'sát, đánh giá hiệu quả sử dụng vốn đầu tư công của các chương '
          'trình, dự án đầu tư trên địa bàn;\n'
          'd) Chủ trì, phối hợp với các cơ quan tổng hợp, đánh giá, báo cáo '
          'tình hình thực hiện dự án đầu tư theo phương thức đối tác công tư '
          'thuộc phạm vi quản lý của địa phương;\n'
          'đ) Làm đầu mối ứng dụng và triển khai Hệ thống thông tin và cơ sở '
          'dữ liệu quốc gia và của tỉnh về đầu tư công trong hoạt động quản lý '
          'nhà nước về đầu tư công tại địa phương;\n'
          'e) Làm thường trực Hội đồng thẩm định báo cáo đề xuất chủ trương '
          'đầu tư các chương trình, dự án và báo cáo nghiên cứu tiền khả thi '
          'dự án đầu tư công, nguồn vốn và khả năng cân đối vốn theo quy định '
          'pháp luật về Đầu tư công.\n'
          'g) Làm thường trực Hội đồng thẩm định cấp cơ sở dự án đầu tư theo '
          'phương thức đối tác công tư; đầu mối tiếp nhận, thẩm định các dự án '
          'đầu tư theo phương thức đối tác công tư thuộc phạm vi quản lý của '
          'địa phương trong trường hợp được Ủy ban nhân dân tỉnh giao và thực '
          'hiện nhiệm vụ theo quy định của pháp luật về đầu tư theo phương '
          'thức đối tác công tư;\n'
          'h) Làm đầu mối đăng tải thông tin dự án đầu tư theo phương thức đối '
          'tác công tư; thẩm định hồ sơ mời sơ tuyển, kết quả sơ tuyển, hồ sơ '
          'mời thầu, hồ sơ yêu cầu, hồ sơ mời đàm phán, danh sách nhà đầu tư '
          'đáp ứng yêu cầu về kỹ thuật, kết quả lựa chọn nhà đầu tư trong '
          'trường hợp các nội dung này được Ủy ban nhân dân tỉnh phê duyệt;\n'
          'i) Chủ trì tham mưu xử lý tình huống trong lựa chọn nhà đầu tư dự '
          'án đầu tư theo phương thức đối tác công tư; chủ trì tổ chức kiểm '
          'tra, giám sát, theo dõi việc thực hiện các quy định của pháp luật '
          'về đầu tư theo phương thức đối tác công tư đối với các dự án trên '
          'địa bàn tỉnh; tham gia Hội đồng tư vấn giải quyết kiến nghị cấp địa '
          'phương theo quy định của pháp luật về đầu tư theo phương thức đối '
          'tác công tư.',
  'treeId': 'điều2'},
 {'khoanId': '8',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '8. Về quản lý đầu tư trong nước và đầu tư nước ngoài\n'
          'a) Cấp, điều chỉnh, thu hồi Giấy chứng nhận đăng ký đầu tư đối với '
          'dự án đầu tư ngoài khu công nghiệp, khu chế xuất, khu công nghiệp '
          'cao, khu kinh tế và các trường hợp khác theo quy định của pháp luật '
          'về đầu tư;\n'
          'b) Làm đầu mối tiếp nhận hồ sơ đề nghị chấp thuận, điều chỉnh chủ '
          'trương đầu tư, chấp thuận nhà đầu tư theo quy định của pháp luật về '
          'đầu tư; làm đầu mối thực hiện nhiệm vụ về giám sát, đánh giá đầu tư '
          'của tỉnh; hướng dẫn thực hiện giám sát, đánh giá đầu tư đối với các '
          'cấp, đơn vị trực thuộc, các dự án được Ủy ban nhân dân tỉnh phân '
          'cấp hoặc ủy quyền cho cấp dưới quyết định đầu tư;\n'
          'c) Quản lý hoạt động đầu tư trong nước và đầu tư nước ngoài vào địa '
          'bàn tỉnh theo quy định của pháp luật; Giải quyết theo thẩm quyền '
          'hoặc trình cấp có thẩm quyền giải quyết khó khăn, vướng mắc của nhà '
          'đầu tư tại địa phương; làm đầu mối giúp Ủy ban nhân dân tỉnh quản '
          'lý nhà nước về công tác xúc tiến đầu tư; tổ chức hoạt động xúc tiến '
          'đầu tư theo kế hoạch đã được Ủy ban nhân dân tỉnh phê duyệt; hướng '
          'dẫn thủ tục đầu tư theo thẩm quyền;\n'
          'd) Thu thập, lưu trữ, quản lý thông tin về đăng ký đầu tư; thực '
          'hiện việc chuẩn hoá dữ liệu, cập nhật dữ liệu về đăng ký đầu tư vào '
          'cơ sở dữ liệu quốc gia về đầu tư; hướng dẫn tổ chức kinh tế thực '
          'hiện dự án đầu tư sử dụng Hệ thống thông tin quốc gia về đầu tư; '
          'báo cáo Bộ Tài chính và Ủy ban nhân dân tỉnh về tình hình tiếp '
          'nhận, cấp, điều chỉnh, thu hồi Giấy chứng nhận đăng ký đầu tư, tình '
          'hình hoạt động của các dự án đầu tư thuộc phạm vi quản lý; tổ chức, '
          'giám sát và đánh giá thực hiện chế độ báo cáo đầu tư tại địa '
          'phương.',
  'treeId': 'điều2'},
 {'khoanId': '9',
  'partId': '2',
  'partType': 'điều',
  'text': 'Điều 2. Nhiệm vụ và quyền hạn\n'
          '9. Về quản lý vốn ODA, nguồn vốn vay ưu đãi của các nhà tài trợ '
          'nước ngoài và các nguồn viện trợ không hoàn lại không thuộc hỗ trợ '
          'phát triển chính thức của các cơ quan, tổ chức, cá nhân nước ngoài\n'
          'a) Tham mưu Ủy ban nhân dân tỉnh phối hợp với Bộ Tài chính, các bộ, '
          'ngành và các cơ quan có liên quan xây dựng chiến lược, định hướng, '
          'kế hoạch vận động, thu hút, điều phối quản lý nguồn vốn ODA, nguồn '
          'vốn vay ưu đãi của các nhà tài trợ và các nguồn viện trợ không hoàn '
          'lại không thuộc hỗ trợ phát triển chính thức của các cơ quan, tổ '

Run Embedding

In [14]:
for document in tqdm(documents):
    list_dieu = document.get("list_dieu", [])
    texts = [f"passage: {dieu['text']}" for dieu in list_dieu]

    if not texts:
        document["list_dieu_vector"] = []
        continue

    vectors = model.encode(
        texts,
        batch_size=8,
        normalize_embeddings=True,
        show_progress_bar=False
    )

    document["list_dieu_vector"] = []

    for dieu, vector in zip(list_dieu, vectors):
        document["list_dieu_vector"].append({
            "partId": dieu["partId"],
            "partType": dieu["partType"],
            "treeId": dieu["treeId"],
            "text": dieu["text"],
            "vector": vector.tolist()
        })

  0%|          | 0/170824 [00:00<?, ?it/s]

AcceleratorError: CUDA error: out of memory
Search for `cudaErrorMemoryAllocation' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
For more detailed error information, run with CUDA_LOG_FILE=stderr